### ISSUE TITLE
Number field doesn't support comma as decimal separator with certain browser locales

### ISSUE THREAD

**Issue by Kehet** [Donkie/Spoolman#102]
When I click the filament density field and type "1,24" it replaces the value automatically with "124". I expect it to either do nothing or replace a comma with a dot. 

This seems to happen because in https://github.com/Donkie/Spoolman/blob/8e9ca8e30544c929cfbe140e06654928bc5863af/client/src/utils/parsing.tsx#L9-L21 function tries to guess decimal separator character based on browser local which in my case is incorrect. I would suggest removing this logic, since I can't see how it would break other locales. 

---

Firefox 117.0 (64-bit)
Spoolman 0.11.0
Microsoft Windows 11 Pro 10.0.22621 Build 22621

![image](https://github.com/Donkie/Spoolman/assets/1544301/d798d56c-41b8-4142-9094-853595ea961e)
![image](https://github.com/Donkie/Spoolman/assets/1544301/d0ca836d-7dca-4b4b-8363-187110ff494e)

**Comment by Donkie** [comment]
I have made another pass at this now, please test it out by swapping out the docker image with `ghcr.io/donkie/spoolman:edge` and see if it works as you'd expect it now.

**Comment by Kehet** [comment]
Awesome, it seems to be working now!
