### ISSUE TITLE
[FR] Use Weblate to facilitate translation 

### ISSUE THREAD

**Issue by Daviteusz** [Donkie/Spoolman#106]
I translate Spoolman using Weblate because it is a very convenient program for translators and is overall perfect for this project.

When the translation is completed, e.g. every 12 hours, the changes are automatically sent as a Pull Request (or commit). The entire operation rests on the shoulders of the weblate bot, translators don't need to know git usage to add new translations or update them.

The official Weblate server can host open-source projects for free.

### My version control settings:
![obraz](https://github.com/Donkie/Spoolman/assets/11527277/94b70884-5f74-4562-b573-f69e8aae1d5e)

### Files settings (ignore my `language filter`, use default)
![obraz](https://github.com/Donkie/Spoolman/assets/11527277/3fd36c6d-82f1-407e-b9f1-69ecefc327af)

### Some screenshots:
<img src=https://github.com/Donkie/Spoolman/assets/11527277/30225c84-16de-49cb-8a65-236707e32b22 width=30%>
<img src=https://github.com/Donkie/Spoolman/assets/11527277/3d0b07fe-700e-46d0-b633-ce5183f05553 width=30%>
<img src=https://github.com/Donkie/Spoolman/assets/11527277/3782930c-0b05-4b20-b840-01db6a4f1f5a width=30%>
<img src=https://github.com/Donkie/Spoolman/assets/11527277/26d8cb1a-5632-484d-b7f8-93271c092de1 width=30%>
<img src=https://github.com/Donkie/Spoolman/assets/11527277/1a4c9fd9-7840-4f92-82c6-d8cf61c1f5ff width=30%>
<img src=https://github.com/Donkie/Spoolman/assets/11527277/3db6ffac-0a22-4757-9bf7-4a0452b4590b width=30%>
<img src=https://github.com/Donkie/Spoolman/assets/11527277/a3794543-2759-4460-ab59-0953540e79f1 width=30%>

**Comment by Donkie** [comment]
If you want machine translated localization, you might as well just use your browser's built-in translation. It would be just as good.

**Comment by Daviteusz** [comment]
@Donkie My suggestion is not related to machine translation but to making translation easier for translators. It is probably better to use a GUI instead of manually agonizing over files in notepad.

**Comment by Donkie** [comment]
Oh I completely misunderstood then. Yes that's definitely on my to-do list to implement a dedicated service to do this :)

**Comment by Donkie** [comment]
Weblate is now up and running :) https://hosted.weblate.org/projects/spoolman/
