### ISSUE TITLE
Dates from API output are missing UTC time zone indicator

### ISSUE THREAD

**Issue by pedrolamas** [Donkie/Spoolman#114]
Following up on this [Fluidd issue](https://github.com/fluidd-core/fluidd/issues/1178), I have now realized that the date & times returned by the Spoolman API are missing the time zone indicator as per [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

Spoolman documentation states that all dates are UTC time zone based, but the serialized representation does not convey that - and I believe this to be incorrect!

For example, calling `/api/v1/spool`, we get a list of spools and I can see the data in all date fields have no time zone indication:

![image](https://github.com/Donkie/Spoolman/assets/85504/28c89ee9-7210-44f1-8b7e-bcff9084e846)

As these are all UTC dates & times, these strings should end with a single "Z" - following the ISO and thus solving this issue in Fluidd and any other frontend.

As an example, lets take the first date from that example, "2023-07-30T10:59:52", and assume that my system is using Europe/London time zone which is currently UTC+1 as per British Summer Time.

Here's what I get in JavaScript by using the `Date` constructor:

![image](https://github.com/Donkie/Spoolman/assets/85504/f67b95eb-070f-4aa8-a3b4-0526a86966a6)

On the first example, as there is no indication of time zone, `Date` will assume that it is on local time and parse and convert to UTC.

On the second example, I just suffixed the date with "Z" so that the `Date` constructor understands that I am indeed passing an UTC value, so no conversion is needed.

**Comment by Donkie** [comment]
Ah yes that is indeed a miss. I will make sure the right timezone marker is added.

**Comment by Ocraftyone** [comment]
@Donkie This issue still persists. It seems that the local time to UTC conversion is doubled up somewhere. When I edit the spool and set last used to the current time (using the GUI), upon save, it is converted to UTC. The GUI then shows the converted UTC time as local time. Then when you poll the API, the already converted UTC time is then converted again. I will provide screenshots of what I am seeing below.

Set to now (current local time)
![image](https://github.com/Donkie/Spoolman/assets/24759591/5be707b3-a583-4e1f-b17f-6b8a903840fe)

Click Save

Spools home page shows converted time
![image](https://github.com/Donkie/Spoolman/assets/24759591/00f7a12e-6ab5-4ac6-bf24-ce5d2b6ce915)

And so does the edit page for the spool
![image](https://github.com/Donkie/Spoolman/assets/24759591/36f6f531-0ca4-4667-9727-f182d8ebb178)

When the API is polled (/api/v1/spool), the result is

`[
  {
    "id": 1,
    "registered": "2023-09-25T11:13:20Z",
    "last_used": "2023-09-25T11:26:43.540000Z",
    "filament": {
      "id": 1,
      "registered": "2023-09-25T11:12:56Z",
      "name": "asdf",
      "vendor": {
        "id": 1,
        "registered": "2023-09-25T11:12:28Z",
        "name": "asdf"
      },
      "material": "PLA",
      "price": 28,
      "density": 1.24,
      "diameter": 1.75
    },
    "used_weight": 800,
    "used_length": 268226.89553341153,
    "archived": false
  }
]`
