### ISSUE TITLE
fail start upgrade on docker compose

### ISSUE THREAD

**Issue by platini76** [Donkie/Spoolman#120]
root@docker:~#  docker-compose pull && docker-compose up -d.
-bash: docker-compose: command not found

can you give me suggestion? I am in  docket ct on proxmoz

**Comment by Donkie** [comment]
Does "docker compose" work? Without the dash.

**Comment by platini76** [comment]
please gibe me a sample commandi

**Comment by Donkie** [comment]
Please look up guides on the internet for how to use docker compose before you move on.

**Comment by platini76** [comment]
I looked on them but all they say about compose admin and other stuff.
can you please help me with the command I have to make... please I am a noob..

**Comment by platini76** [comment]
I am a noob but the command in guide for me is wrong...
correct is:
docker compose pull && docker compose up -d

but I still have an error:

root@docker:~#  docker compose pull && docker compose up -d
[+] Pulling 10/11
 ⠧ spoolman 10 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulling                                             8.7s 
   ✔ 7264a8db6415 Already exists                                                                       0.0s 
   ✔ 66e1d5e70e42 Already exists                                                                       0.0s 
   ✔ 0448660c92fc Download complete                                                                    3.4s 
   ✔ 3ce23f846e31 Download complete                                                                    0.7s 
   ✔ efebc2e683d2 Download complete                                                                    1.7s 
   ✔ ecb6b39d75b3 Download complete                                                                    2.1s 
   ✔ d695f06f17dd Download complete                                                                    2.4s 
   ✔ 430f31cd7345 Download complete                                                                    3.9s 
   ✔ 0d3afd784557 Download complete                                                                    7.0s 
   ✔ 4f4fb700ef54 Download complete                                                                    3.9s 
failed to register layer: Error processing tar file(exit status 1): replaceDirWithOverlayOpaque("/etc/terminfo") failed: createDirWithOverlayOpaque("/etc/rdwoo892275739") failed: failed to mkdir /etc/rdwoo892275739/m/d: mkdir /etc/rdwoo892275739/m/d: invalid argument

**Comment by platini76** [comment]
and when I tried to up :

root@docker:~# docker compose up -d
[+] Running 2/2
 ✔ Network root_default       Created                                                                  0.1s 
 ✔ Container root-spoolman-1  Created                                                                  9.6s 
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown

**Comment by platini76** [comment]
finally solved but with command:
docker compose pull && docker compose up -d
