### ISSUE TITLE
Spoolman Time/Date issues

### ISSUE THREAD

**Issue by Ocraftyone** [Donkie/Spoolman#124]
Issue #114 still is not completely fixed. It seems that the local time to UTC conversion is doubled up somewhere. When I edit the spool and set last used to the current time (using the GUI), upon save, it is converted to UTC. The GUI then shows the converted UTC time as local time. Then when you poll the API, the already converted UTC time is then converted again. I will provide screenshots of what I am seeing below.

Set to now (current local time)
![image](https://github.com/Donkie/Spoolman/assets/24759591/5be707b3-a583-4e1f-b17f-6b8a903840fe)

Click Save

Spools home page shows converted time
![image](https://github.com/Donkie/Spoolman/assets/24759591/00f7a12e-6ab5-4ac6-bf24-ce5d2b6ce915)

And so does the edit page for the spool
![image](https://github.com/Donkie/Spoolman/assets/24759591/36f6f531-0ca4-4667-9727-f182d8ebb178)

When the API is polled (/api/v1/spool), the result is

<details>
<summary>JSON Response</summary>

[
  {
    "id": 1,
    "registered": "2023-09-25T11:13:20Z",
    "last_used": "2023-09-25T11:26:43.540000Z",
    "filament": {
      "id": 1,
      "registered": "2023-09-25T11:12:56Z",
      "name": "asdf",
      "vendor": {
        "id": 1,
        "registered": "2023-09-25T11:12:28Z",
        "name": "asdf"
      },
      "material": "PLA",
      "price": 28,
      "density": 1.24,
      "diameter": 1.75
    },
    "used_weight": 800,
    "used_length": 268226.89553341153,
    "archived": false
  }
]

</details>

Edit: Replaced code block with collapsed section bc the code block made it a readability nightmare
Also, this was done on a clean instance of Spoolman

**Comment by Donkie** [comment]
Thank you, I will look into this

**Comment by Donkie** [comment]
@Ocraftyone @Disane87 can you please try the edge tag and see if it works correctly now? I've fixed some issues that I found.

**Comment by Disane87** [comment]
Yeah sure. Will do it in the next few days.

**Comment by Disane87** [comment]
Looks way better now @Donkie:
![image](https://github.com/Donkie/Spoolman/assets/956158/644d68f0-6e2a-413f-8507-579234a0ca60)

![image](https://github.com/Donkie/Spoolman/assets/956158/7a9f9d48-a485-4744-a9cd-24557b704fdf)
