### ISSUE TITLE
Install instructions fix

### ISSUE THREAD

**Issue by mlee12382** [Donkie/Spoolman#130]
I just installed Spoolman and I noticed that the current version of Docker uses "docker composer" instead of "docker-composer" this may cause confusion for those that aren't familiar with using Docker. Fortunately I was able to find the solution but it took a bit of searching to do so. Updating the install instructions or adding a note that it may be different depending on your version of Docker might be helpful.

Thanks for the good work on this plugin, it has been the only thing I have missed from running Octoprint.

**Comment by locki-cz** [comment]
all is there: [https://github.com/Donkie/Spoolman/issues/12](url)

**Comment by mlee12382** [comment]
The issue is that the instructions in the README.md on here reference an old command that no longer works and does more harm than good for people who are new to docker. They should be corrected or a link added pointing to the issue you shared.

**Comment by Donkie** [comment]
I have fixed it now :)

**Comment by mlee12382** [comment]
> I have fixed it now :)

Thanks! 🙂 I'm working on an install script and some additional macros to try and make things easier and more integrated. 
The install script I'm setting up should install docker and do all the folder and container creation and launch it. It should make the whole process a lot easier for beginners. 
I've set up macros on my printers that grab the spool ID from the filament start gcode in the slicer and check if it matches the spools loaded in the printer on my ercf printer and if not it pauses and waits for user interaction to check and make sure it's correct.  On my non ercf printer, it just uses that same ID in the filament profiles to set the active spool. 
I will be publishing them for others to use, or I could provide them to you to include here if you would like?

**Comment by Donkie** [comment]
You're welcome to add them to the project via a pull request if you want! It can be part of the official instructions.

**Comment by mlee12382** [comment]
> You're welcome to add them to the project via a pull request if you want! It can be part of the official instructions.

I will definitely do that once I have them ready :) 
Any idea when or if Mainsail will integrate spoolman?

**Comment by Donkie** [comment]
Sweet! 
The mainsail release from yesterday includes support for it :)

**Comment by mlee12382** [comment]
Ohhh! Very nice. I must have missed that. Thanks again!
