### ISSUE TITLE
Add fields for retraction distance, retraction speed, pressure advance factor, flow/extrusion multiplier

### ISSUE THREAD

**Issue by Luro02** [Donkie/Spoolman#132]
### Motivation

There are some settings that change based on the used filament like retraction or print temperature. For now I have a CURA material profile for each filament. This solution works well, when you only have one printer, or are the only person using the printer. Sharing the material profiles with other people is suboptimal (it is easy for them to have outdated versions, not everyone is proficient with git).

Klipper supports firmware retractions and setting the pressure advance factor on the printer. The workaround solution seems to be, to create a `gcode_macro` for each filament that sets the values. When you have 10-20 spools, creating a macro for each and finding the right one in the interface becomes difficult.

Ideally, you could select your spool when changing filament and it will automatically apply the settings. Spoolman is integrated into KlipperScreen, Moonraker, Fluidd and (in the future) Mainsail. Therefore it does not make sense to create another project, when one already exists.

Before I can make an issue in Mainsail or KlipperScreen to change the settings based on the data in spoolman, the data should be available in spoolman.

### Solution

Add fields for
- Retraction Distance
- Retraction Speed
- Pressure Advance Factor
- (Pressure Advance Smooth Time Range)
- Flow/Extrusion multiplier

**Comment by Donkie** [comment]
Also already mentioned in #20

**Comment by Luro02** [comment]
Firmware Retraction Distance/Speed: [`SET_RETRACTION`](https://www.klipper3d.org/G-Codes.html#firmware_retraction)
Pressure Advance Factor/(Pressure Advance Smooth Time Range): [`SET_PRESSURE_ADVANCE`](https://www.klipper3d.org/G-Codes.html#set_pressure_advance)

Those are the ones that make sense to automatically apply, because they are extra commands that do not influence the entire gcode.

### retractions

If firmware retractions are **not** used, the gcode should not be changed. That would be difficult to implement correctly and is unexpected behavior. That should not be a problem, because one can easily enable firmware retractions in klipper/slicer. (In Cura there is a klipper extension with which, you just have to tick a checkbox)

Detecting if firmware retractions are enabled, should not be too difficult. The gcode_macro KAMP emits a warning, when they are disabled (should be the purge line macro?). In that case, one could show a popup or a message that retractions will not be changed.

On printers where firmware retractions are enabled, one could still print gcode that does not have firmware retracts. In those cases, I would not change anything. There must be a reason why firmware retractions are not used for those gcodes.

### flow

Flow/Extrusion multiplier: [Klipper supports M221](https://www.klipper3d.org/G-Codes.html)

Not sure if that should be applied automatically. If I specify a flow of 93% in cura, will that emit an M221 with the value or does it affect a lot of gcode instructions?

This one does not matter that much, because most filaments should have a 100% flow. Would have been nice to be able to look up the flow, but I could add those those as comments.

**Comment by Luro02** [comment]
In #20 there is a link to a cfg https://github.com/Donkie/Spoolman/issues/20#issuecomment-1615835218 which shows how the parameters could be applied https://github.com/fbeauKmi/V2.3934/blob/39c39326a271ea4991ef06fa09d6830e2d039aa0/klipper_config/macros/helpers/db_filament.cfg#L336

(Not sure about the temperature one, especially because temperature could be different for initial layer and the following)

**Comment by Benoitone** [comment]
> 
> Add fields for
> 
> - Retraction Distance
> 
> - Retraction Speed
> 
> - Pressure Advance Factor
> 
> - (Pressure Advance Smooth Time Range)
> 
> - Flow/Extrusion multiplier

I think that adding fields also for:

- unretract_speed

- unretract_extra_length

- filter fan speed

- additional_z_offset

Would be good 😊

**Comment by RockNLol** [comment]
All these parameters are also heavily printer dependent. I think they make more sense stored on the machine than in spoolman. Most of those can be changed during runtime with a macro in klipper, and could be loaded from a config file in a FILAMENT_LOAD macro, similar to the pressure advance setup seen here:
https://github.com/zellneralex/klipper_config/blob/master/pressure_advance.cfg

**Comment by alexandrkut** [comment]
> All these parameters are also heavily printer dependent. I think they make more sense stored on the machine than in spoolman. Most of those can be changed during runtime with a macro in klipper, and could be loaded from a config file in a FILAMENT_LOAD macro, similar to the pressure advance setup seen here: https://github.com/zellneralex/klipper_config/blob/master/pressure_advance.cfg

If we have many printers with the shared filament base, then it is more convenient to store the retract, pa, la in the filament base.

**Comment by spyder007** [comment]
Can't this be covered with custom fields for the filament?
