### ISSUE TITLE
Custom sorting tabs in lists show filament colour in box

### ISSUE THREAD

**Issue by locki-cz** [Donkie/Spoolman#14]
Custom sorting tabs in lists, also sort filament by name type, vendor, colour, show filament colour in box, posible hide some not need tabs. It helps for search in lots of spools! :)

It would be nice if the filament color was also displayed in the lists, as it is on the octoprint.

![listSpools-tab](https://github.com/Donkie/Spoolman/assets/30490842/02d98592-c954-434e-86b3-0a8134f52ef1)

Colour tab, please make it little bit biger and wider :)

Thank you

**Comment by Donkie** [comment]
Sorting/filtering is now available. I will create new issues for the remaining feature requests in this issue
