### ISSUE TITLE
Filamant usage

### ISSUE THREAD

**Issue by Macfiller** [Donkie/Spoolman#151]
When i have added the filamant and the spool grams it will use more then i putted in.
Like the filamant roll was 1kg, used over 750 grams, so left 250 grams, and putted the weight with the spool holder in its ways 1257 grams. But when i print like an yxz cube of 4.8 grams it thinks it take all of the 250 grams left. Idontknow if i am doing something wrong.

![inbound1816538240513952849](https://github.com/Donkie/Spoolman/assets/147885183/6dfc63c0-7289-43c0-8ce9-580ee8973dde)

https://github.com/Donkie/Spoolman/assets/147885183/5ce80261-ab61-4e47-96bd-c809958fae4b

https://github.com/Donkie/Spoolman/assets/147885183/c25aa8a3-18cc-4890-b975-37f7703d7603

**Comment by Donkie** [comment]
What is your density and diameter set to in the filament's settings?

**Comment by Macfiller** [comment]
Density is 1.24 and diameter 1.75

**Comment by Macfiller** [comment]
Isseu is fixed, resinstalled the software now its working good! Thanks @Donkie
