### ISSUE TITLE
Manual usage entry >=1000g impossible

### ISSUE THREAD

**Issue by fweber3** [Donkie/Spoolman#155]
**Description:**
It is impossible to manually enter a "Used Weight" of >=1000g on the "Edit Spool" page. Numbers >=1000 get divided by 1000, thus making "Used Weight" >=1000g impossible. This is usually accompanied by additional minor number entry weirdness.

**Expected behaviour:**
It should be possible to manually enter a "Used Weight" of at least 2700g (very likely even more, but that is my personal usecase), and have it be used correctly.

**Example:**
Manual entry 134 ---> display 134 ---> stored value 134
Manual entry 1345 ---> display 1.345 ---> stored value 1,3 (divide by 1000)
Manual entry 1345, ---> display 1,345 ---> stored value 1,3 (interplay of separators)
Manual entry 1345,6 ---> display 1,346 ---> stored value 1,3 (last decimal)
Manual entry 1345,67 ---> display 1,347 ---> stored value 1,3 (last decimal)

**Details:**
- I can enter any relevant number into the edit field (max. 4 digits, no decimals).
- 1. The thousands-separator is created automatically (by the edit field?) and correctly, according to locale.
- 2. It may also be entered manually. If put into a wrong position that will be corrected automatically. It is not possible to omit it.
- Upon pressing enter or changing focus, the number visible in the field changes:
- 1. the thousands separator changes into a decimal separator
- 2. to the right of the new decimal separator, all but two digits are cut off and rounded. The rounding is mathematically correct. Separators in the cut-off part do not seem to play any role.
- Manually entering the same number with flipped separators (as if from a different locale) does not change the outcome.
- The new number will then be used without any problems (except for being factually wrong).

My system and browsing locale is German: thousands-separators are "." (dot) and decimal separators are "," (comma). Spoolman is set to German.

Versions: Spoolman 0.11.0 (in docker on RaspberryPi), Firefox 115.3.1esr (on Debian Linux)

**Comment by TomW1605** [comment]
can you please try updating and see if that fixes the issue? the spool weight entry ui got overhauled in v0.12.0 and i cant reproduce the bug in the new ui

**Comment by fweber3** [comment]
I updated to Spoolman 0.12.2. The issue is fixed there, anything ( even stupid stuff ) I threw at it looks sane.
Could've thought of updating myself, thank you for your help.

PS: I very much like the new switch for which spool weight to use! 👍
