### ISSUE TITLE
Moonraker Update Manager

### ISSUE THREAD

**Issue by Marshalldog** [Donkie/Spoolman#156]
running a voron install with spoolman. I was wondering if it was possible to manage updates for spoolman via klipper (maybe moonraker)?

**Comment by rdany62** [comment]
Maybe we can copy and past the update commands into a script and use that script in moonraker.conf ?
Will try it tomorow 🙂

**Comment by fjpanag** [comment]
> Maybe we can copy and past the update commands into a script and use that script in moonraker.conf ? Will try it tomorow 🙂

Have you had any success with it?

I guess we need the following in moonraker?
(Assuming it is cloned as a git repo)

```
[update_manager Spoolman]
type: git_repo
path: ~/Spoolman
origin: https://github.com/Donkie/Spoolman.git
managed_services: Spoolman
install_script: scripts/install_debian.sh
```

**Warning!** I haven't tested this!

**Comment by Donkie** [comment]
It's unfortunately not that simple, since you also need to built the web client frontend. Just cloning the git repo isn't sufficient.
I will look into how this could be done properly

**Comment by rdany62** [comment]
> > Maybe we can copy and past the update commands into a script and use that script in moonraker.conf ? Will try it tomorow 🙂
> 
> Have you had any success with it?
> 
> I guess we need the following in moonraker?
> (Assuming it is cloned as a git repo)
> 
> ```
> [update_manager Spoolman]
> type: git_repo
> path: ~/Spoolman
> origin: https://github.com/Donkie/Spoolman.git
> managed_services: Spoolman
> install_script: scripts/install_debian.sh
> ```
> 
> **Warning!** I haven't tested this!

Hi,

Sorry I had a problem with the laptop running klippy I had to change it,as all components are soldered on mainboard which doesn't power up anymore I had to reinstall everything (no backup 😁)

**Comment by rdany62** [comment]
> It's unfortunately not that simple, since you also need to built the web client frontend. Just cloning the git repo isn't sufficient.
> I will look into how this could be done properly
> 
> Edit: I saw now you try to run the install shell script. However the install_script field doesn't work like that in Moonraker unfortunately, so it will not work anyway.

The install script isn't fully unattented and installs everything instead of updating, that's why it will not work, is that right ?

To update directly from moonraker we need to update the git repo and rebuild the client front-end. Does it need to be done with pdm ?

**Comment by Donkie** [comment]
No, the install_script line isn't executing any shell code at all if I understand correctly.

Neverless, I have pushed some commits to automate building the client and packaging it in a way so that Moonraker would be able to update it using the "web" type. So this will come soon :)

**Comment by rdany62** [comment]
> No, the install_script line isn't executing any shell code at all if I understand correctly.
> 
> Neverless, I have pushed some commits to automate building the client and packaging it in a way so that Moonraker would be able to update it using the "web" type. So this will come soon :)

Thanks 😉
I will try as soon as it comes, let us know 😊

**Comment by Donkie** [comment]
This is now added in the latest update :)

Add this to your Moonraker.conf (update `path` accordingly):
```yml
[update_manager spoolman]
type: web
channel: stable
repo: Donkie/Spoolman
path: ~/Spoolman
```

**Comment by TMTYD** [comment]
So the Spoolman update works in the Mainsail Update Manager?
