### ISSUE TITLE
QR code Camer Scan dont work on http

### ISSUE THREAD

**Issue by Robnex** [Donkie/Spoolman#162]
Hello,

System:
My spoolman launched as http://ip:7912 on docker
I could create a spoolman qr.

Problem:
But when i click on the camera button on the bottom right i get the message:
"The page is not served over HTTPS" and the camera dont open.

Solution:
it should work with http

Greetings Robnex

**Comment by Donkie** [comment]
It cannot work with http due to web browser security restrictions. It's not a limitation put in place by me.

**Comment by Robnex** [comment]
And whats the solution for this? Lets encryt to https?

Does moonraker work when the page is on https?

**Comment by Donkie** [comment]
Yes, either let's encrypt or use a self-signed certificate. There are many guides online on how to setup e.g. nginx as a reverse proxy to add https to a service.

Yes it should work fine.
