### ISSUE TITLE
Runs fine when started manually in ssh with a terminal window up

### ISSUE THREAD

**Issue by Eka157** [Donkie/Spoolman#163]
Runs fine when started manually in ssh with a terminal window up, below is log from attempting to run it as systemd on startup:

Oct 21 13:55:04 VORON systemd[765]: Started Spoolman.
Oct 21 13:55:04 VORON systemd[16967]: Spoolman.service: Failed to locate executable /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 13:55:04 VORON systemd[16967]: Spoolman.service: Failed at step EXEC spawning /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 13:55:04 VORON systemd[765]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 21 13:55:04 VORON systemd[765]: Spoolman.service: Failed with result 'exit-code'.
Oct 21 13:55:04 VORON systemd[765]: Spoolman.service: Scheduled restart job, restart counter is at 4.
Oct 21 13:55:04 VORON systemd[765]: Stopped Spoolman.
Oct 21 13:55:04 VORON systemd[765]: Started Spoolman.
Oct 21 13:55:04 VORON systemd[16968]: Spoolman.service: Failed to locate executable /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 13:55:04 VORON systemd[16968]: Spoolman.service: Failed at step EXEC spawning /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 13:55:04 VORON systemd[765]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 21 13:55:04 VORON systemd[765]: Spoolman.service: Failed with result 'exit-code'.
Oct 21 13:55:05 VORON systemd[765]: Spoolman.service: Scheduled restart job, restart counter is at 5.
Oct 21 13:55:05 VORON systemd[765]: Stopped Spoolman.
Oct 21 13:55:05 VORON systemd[765]: Spoolman.service: Start request repeated too quickly.
Oct 21 13:55:05 VORON systemd[765]: Spoolman.service: Failed with result 'exit-code'.
Oct 21 13:55:05 VORON systemd[765]: Failed to start Spoolman.
Oct 21 15:29:13 VORON systemd[765]: Started Spoolman.
Oct 21 15:29:13 VORON systemd[29027]: Spoolman.service: Failed to locate executable /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 15:29:13 VORON systemd[29027]: Spoolman.service: Failed at step EXEC spawning /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 15:29:13 VORON systemd[765]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 21 15:29:13 VORON systemd[765]: Spoolman.service: Failed with result 'exit-code'.
Oct 21 15:29:14 VORON systemd[765]: Spoolman.service: Scheduled restart job, restart counter is at 1.
Oct 21 15:29:14 VORON systemd[765]: Stopped Spoolman.
Oct 21 15:29:14 VORON systemd[29029]: Spoolman.service: Failed to locate executable /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 15:29:14 VORON systemd[29029]: Spoolman.service: Failed at step EXEC spawning /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 15:29:14 VORON systemd[765]: Started Spoolman.
Oct 21 15:29:14 VORON systemd[765]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 21 15:29:14 VORON systemd[765]: Spoolman.service: Failed with result 'exit-code'.
Oct 21 15:29:14 VORON systemd[765]: Spoolman.service: Scheduled restart job, restart counter is at 2.
Oct 21 15:29:14 VORON systemd[765]: Stopped Spoolman.
Oct 21 15:29:14 VORON systemd[765]: Started Spoolman.
Oct 21 15:29:14 VORON systemd[29030]: Spoolman.service: Failed to locate executable /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 15:29:14 VORON systemd[29030]: Spoolman.service: Failed at step EXEC spawning /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory
Oct 21 15:29:14 VORON systemd[765]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 21 15:29:14 VORON systemd[765]: Spoolman.service: Failed with result 'exit-code'.
Oct 21 15:29:14 VORON systemd[765]: Spoolman.service: Scheduled restart job, restart counter is at 3.
Oct 21 15:29:14 VORON systemd[765]: Stopped Spoolman.
Oct 21 15:29:14 VORON systemd[765]: Started Spoolman.
Oct 21 15:29:14 VORON systemd[29031]: Spoolman.service: Failed to locate executable /home/v2.4183/Spoolman/scripts/scripts/start.sh: No such file or directory

**Comment by Eka157** [comment]
tried to add a new folder under /scripts/ to have another subfolder named /scripts/ where i put a new copy of start.sh. no effect

**Comment by Donkie** [comment]
Hmm must be some bug in the new installation script. Revert your new subfolder changes, then cd into the spoolman/scripts/ and run `./install_debian.sh` to redo the installation. See if that fixes the service script path

**Comment by Donkie** [comment]
Found the issue and fixed it in 292ecbf1664d123bc9fa0cf5b9a3fa98fa709db6

As a temporary work-around before I release the update, do as I said in the previous comment. CD into the scripts directory and run `bash ./install_debian.sh` instead of what it says in the README.

**Comment by Eka157** [comment]
I reverted my folder changes and entered the following command:

cd Spoolman/scripts
bash ./install_debian.sh

Re installed and then checked log, still the exact same log error. could i replace my existing install_debian.sh with the new one with changes from 292ecbf?

appreciate the fast response, really loving the spool manager (even if i have to keep a terminal window open lol)

**Comment by Donkie** [comment]
Ah yeah you also need to run `systemctl --user daemon-reload` after you have done the reinstall to update the new service configuration. So run that command, then restart the service using `systemctl --user restart Spoolman`. 

See if that helps :)

**Comment by Eka157** [comment]
Tried everything you suggested in previous comment first, no change. Also attempted deleting spoolman folder entirely, re cloning git and then including the new install_debian file (292ecbf). Re installed using commands mentioned previously but resulted in same error.

**Comment by Donkie** [comment]
What do you get if you do: `cat ~/.config/systemd/user/Spoolman.service`?

**Comment by Eka157** [comment]
[Unit]
Description=Spoolman

[Service]
Type=simple
ExecStart=/home/v2.4183/scripts/start.sh
WorkingDirectory=/home/v2.4183
Restart=always

[Install]
WantedBy=default.target

**Comment by Donkie** [comment]
Can the start.sh file be found at `/home/v2.4183/scripts/start.sh`? Where is it located?

**Comment by Eka157** [comment]
no it is in /home/v2.4183/Spoolman/scripts/start.sh, thats where installer put it

**Comment by Eka157** [comment]
tried to create a folder there and copy start.sh into it, same error

**Comment by Donkie** [comment]
Very strange. And you are now using the latest install_debian.sh? E.g, line 168 should look like this:

    script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

A simple temporary fix is to manually edit the `~/.config/systemd/user/Spoolman.service` file and set the ExecStart and WorkingDirectory paths correctly. ExecStart should point to the start.sh script, and WorkingDirectory should point to the Spoolman dir. After that, you can run `systemctl --user daemon-reload` and then restart the service, and it should work.

I would be happy if you could help me debug this further though.

**Comment by Eka157** [comment]
absolutely! im back at the printer and ill give that a go in a minute. I should note that i dont have a whole lot of experience with PI or coding, mainly just what ive done to my voron, so it could very well be something very simple im overlooking.

**Comment by Eka157** [comment]
also unrelated but a list of commands somewhere on the github page would be helpful maybe. like whatever is supposed to pop up with the -help command.

**Comment by Eka157** [comment]
so i edited that file to include the correct paths and then  "cd Spoolman" "systemctl --user start Spoolman" was told to run daemon reload, ran that and then tried to start again. nothing happened so i opened log and had same log lol

**Comment by Seqway** [comment]
> Very strange. And you are now using the latest install_debian.sh? E.g, line 168 should look like this:
> 
> ```
> script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
> ```

Please be kindly informed that in my install_debian.sh file this line 168 WAS NOT there. only the second line was there. I manually updated this install_debian.sh file now with your current changes and startet the file. It takes a while when he finishes on my Pi3b ... I will let you know

**Comment by Seqway** [comment]
I get now a permission denied :-(

Spoolman.service: Failed to locate executable /home/myhome/Spoolman-0.13.0/scripts/start.sh: Permission denied

**Comment by Donkie** [comment]
Ah, that's a miss from me. The scripts should now be executable by default since the latest commit.

For now, you can fix it by doing `chmod +x scripts/start.sh`

**Comment by Seqway** [comment]
Ok, now Spoolman is starting and I can connect to the frontend via browser

**Comment by Eka157** [comment]
i recloned git and reinstalled, all fixed!

**Comment by Eka157** [comment]
is there a way to clear my journalctl log for spoolman? its gotten really long with all this messing around lol

**Comment by Donkie** [comment]
Ok nice!

Clearing journalctl doesnt seem to be trivial, but doable. See https://unix.stackexchange.com/a/194058

Add on `--user Spoolman` to make it target the Spoolman service specifically.
