### ISSUE TITLE
spoolman service is not running at start

### ISSUE THREAD

**Issue by Seqway** [Donkie/Spoolman#165]
Hello,
i installed Spoolman according to the documentation via the install script.
But my spoolman service isn't running and ends up with an error.
Looking to the system log file I see that the service wants to run the

start.sh

in /scrits/scripts but there is no second subfolder scripts. Is this a bug and how can I start it manually ?
Simply starting the script gives me no access to the browser on port 7912

**Comment by Donkie** [comment]
Known bug, see https://github.com/Donkie/Spoolman/issues/163
