### ISSUE TITLE
Standalone installation in CT (LXC) not working (?)

### ISSUE THREAD

**Issue by livinhack** [Donkie/Spoolman#166]
Would it be possible to create a working script for root users?
(I have no idea about that...)

In a CT there is (usually) only the root user...
The script warns at the beginning... but largely runs through. But when you then run start.sh, the .venv folder is missing...

I know Proxmox better than Docker and can look into any CT with Webmin, so it would be really great if that were possible.

Greetings
______________________________________________________________________________________________________________________________

Wäre es möglich ein funktionierendes Script für Root Nutzer zu erstellen?
(Ich hab von sowas keine Ahnung...)

In einer CT gibt es (meist) nur den Root Nutzer...
Das Script warnt am Anfang... läuft aber weitestgehend durch. Wenn man dann aber start.sh ausführt, fehlt der .venv Ordner...

Ich kenne Proxmox besser als Docker und kann mit Webmin in jede CT schauen, daher wäre es echt super, wenn das ginge.

Grüße

**Comment by Donkie** [comment]
Can't you install the docker container since you're using LXC?

**Comment by livinhack** [comment]
Well, that's what I don't want!

**Comment by livinhack** [comment]
First of all: I am not an IT person.

I once read that Docker containers and LXC's have something in common in their base.

I create CT's using the Proxmox interface. I had already tested the effect of choosing such a container as an image for the LXC... Doesn't work! (Well,... That would be too easy...)

I also don't want to run a full Docker in an LXC, because if it works, it ignores the CT restrictions regarding e.g. RAM and uses the full RAM...

No matter whether Pi-Hole, Wire-Guard, Nextcloud or Homer, everything runs on its own LXC, installed normally by hand like on a Linux PC.

So it will work somehow, just unfortunately not with the current script.

**Comment by Donkie** [comment]
I'm not very familiar with proxmox, but couldn't you for instance spin up an Ubuntu 22.04 container in LXC and then install Spoolman as a non-root user in the standalone way, inside this ubuntu container?

**Comment by livinhack** [comment]
I would have to look at that again.  Because of the Nextcloud database user, for example, I think that this should be possible.  But since I always use the root user that is created when setting up an LXC, I have to look into it more.

**Comment by Donkie** [comment]
Could you try the following commands in succession and see if it works?
1. `python3 -m pip install --user --upgrade pip`
2. `pip3 install --user setuptools wheel pdm`

**Comment by Donkie** [comment]
I feel like I know too little to move on from here, and will call quits on this case for now. Someone else with more experience in this environment needs to assist here

**Comment by RockNLol** [comment]
I installed the standalone version successfully in an LXC using a non-root user. Running something like spoolman as root is probably not a good idea anyways. Assuming a Ubuntu LXC and being logged in as root just create a new user with `adduser spoolman` and give it sudo privileges with  `usermod -aG sudo spoolman`. Then change into the new user with `su spoolman` and follow the installation instructions.

**Comment by livinhack** [comment]
I can't say at the moment whether my test LXC was Ubuntu or Debian (proxmox LXC), I had to "install" the sudo function myself... lol.  I had no success with a non-root user.  Can you tell us more about your approach?

**Comment by RockNLol** [comment]
Alright, I've done some testing. It seems it is in fact not working in a freshly installed debian 12 LXC. The install script fails without error in the same place you described at `Updating pip...`.

I succeeded though in a fresh Ubuntu 22.04 LTS LXC. Here are my steps for installation after the initial LXC setup:

1. As root update the system with `apt update && apt upgrade -y`
2. install curl and unzip with `apt install curl unzip`
3. add the new non-root user with `adduser spoolman`
4. add the new user to sudoers group with `usermod -aG sudo spoolman`
5. switch to this user with `su spoolman`
6. switch to the users home directory with `cd`
7. download the latest version of Spoolman with `wget https://codeload.github.com/Donkie/Spoolman/zip/refs/tags/v0.13.1 -O Spoolman.zip`
8. unzip it with `unzip Spoolman.zip`
9. enter the directory with `cd Spoolman-0.13.1`
10. install it with the provided script `bash ./scripts/install-debian.sh`

unfortunately the installation of the systemd service failed with the error "failed to connect to bus: $dbus_session_bus_address and $xdg_runtime_dir not defined", which I have not diagnosed. But to run Spoolman independent from the unprivileged users login you need to set up a systemwide service anyways, by exiting the su session with `exit` and creating a new file at:
`/etc/systemd/system/spoolman.service`
...containing:
`[Unit]
Description=Spoolman

[Service]
Type=simple
ExecStart=/home/spoolman/Spoolman-0.13.1/scripts/start.sh
WorkingDirectory=/home/spoolman/Spoolman-0.13.1
Restart=always
User=spoolman

[Install]
WantedBy=default.target
`
Then running `systemctl start spoolman && systemctl enable spoolman` to launch and enable autostart of spoolman. After this I was able to access the webinterface.

**Comment by stony2k** [comment]
I found a temporary solution to install Spoolman with the script in a Proxmox lxc container (Ubuntu 23.10) via root user.

First I edited the install-debian.sh via nano and removed all "_|| exit 1_." Than I installed to following packages:
apt install python3-pdm
apt install curl

Hope this helps until there is a (maybe) besser solution for the installation. @Donkie Maybe the packages python3-pdm should be checked and installed within the script?

**Comment by Donkie** [comment]
@stony2k yeah I noticed this as well in Debian Bookworm, you can't install user level pip packages, instead you need to use apt-get. I have fixed this in the latest commits, and will release an update later in the week.

**Comment by Donkie** [comment]
Closing this now since it should be working with update 0.14.
Please reopen if that's not the case

**Comment by livinhack** [comment]
Just to share:

I found this today: https://tteck.github.io/Proxmox/#spoolman-lxc
