### ISSUE TITLE
Syntax correction

### ISSUE THREAD

**Issue by ThaPg** [Donkie/Spoolman#167]
Small syntax correction.

_spool.fields.id_ and _filament.fields.id_ are with **ID** (both capital letters)

_vendor.fields.id_ is **Id** (first capital letter, second not capital letter)

I faced the problem when I translated the app with weblate.

It's fantastic work. Congratulations.

**Comment by Donkie** [comment]
Thank you, I have updated the english translation now so it's ID for the vendor as well.
