### ISSUE TITLE
QR code size not uniform when generating labels

### ISSUE THREAD

**Issue by m-klecka** [Donkie/Spoolman#169]
Title explains the issue. Attached picture also shows it. I first thought it was due to, maybe, different number of rows on labels, but thats not the case. There are 3 different size QR codes, if im seeing correctly.
![image](https://github.com/Donkie/Spoolman/assets/118010822/9a06b8df-38ae-4ab9-9dd7-67374fdd9eef)

**Comment by Donkie** [comment]
It's kinda intended for now. It's to give more space to the text.
Styling these labels have been quite hard, but it's planned already to improve it further. https://github.com/Donkie/Spoolman/issues/74

I will close this as duplicate for that reason.
