### ISSUE TITLE
huge amount of filament usage after canceled print

### ISSUE THREAD

**Issue by DanniDesign** [Donkie/Spoolman#174]
So, today i started some prints that i canceled for reasons. But after that (i think it happened because of the cancelled print) the filament usage of the selected filament shot to an insane amount.

I've also e-stopped my printer multiple times and i could check tomorrow if it's because of the cancelled print or e-stop. But i thought that this might be a obvious issue that could be resolved without having to check.
![IMG_2830](https://github.com/Donkie/Spoolman/assets/70161891/09566456-2e0f-4715-8182-b3aa4617f278)

**Comment by clevelandcs** [comment]
This sounds like it could be pretty difficult to debug. My guess from what you describe is that the problem may be on the Moonraker side and that Moonraker is calling the use filament API endpoint multiple times for some reason during e-stop or after restart trying to account for the filament used in that time frame. 

If you could pull the API logs from your spoolman instance during that time it should be possible to tell provided you have the API call logs from the time period you were e-stopping your printer.
