### ISSUE TITLE
Release 0.13.1 missing spoolman-client.zip

### ISSUE THREAD

**Issue by killboxalpha** [Donkie/Spoolman#175]
install script calls for spoolman-client.zip, not included with latest release fails to unzip and exits out of install before completing 

Python 3.9 or later is installed (Current version: 3.9.2)
Updating pip...
Installing Spoolman backend and its dependencies using PDM...
All packages are synced to date, nothing to do.
Installing the project as a package...
  ✔ Update spoolman 0.13.1 -> 0.13.1 successful

🎉 All complete!

Downloading Spoolman web client v0.13.1...
[spoolman-client.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of spoolman-client.zip or
        spoolman-client.zip.zip, and cannot find spoolman-client.zip.ZIP, period.

**Comment by Donkie** [comment]
Thanks for the report, fixed!

**Comment by Seqway** [comment]
and what to do ?
I have the same problem

**Comment by Donkie** [comment]
Should be enough to run the script again.
If you have a spoolman-client.zip in your Spoolman folder, remove it first.
