### ISSUE TITLE
Restart after printing

### ISSUE THREAD

**Issue by Eloura74** [Donkie/Spoolman#176]
Hello everyone,
After each finished print, I have to restart spoolman with the following command:
"
cd Spoolman-0.13.1
yes | bash ./scripts/install_debian.sh
"
because otherwise I no longer have access to my mainsail interface.
Any ideas?
thank you

**Comment by rufinus** [comment]
if you use docker, can you post output of  after print end?
`docker-compose logs --tail -n200`

**Comment by killboxalpha** [comment]
i have the same issues in the standalone install. 

the moonraker log says the spoolman page is unreachable, i've opened a bug in the moonraker github but the only reply stated it's a problem with spoolman. 

https://github.com/Arksine/moonraker/issues/734
[moonraker.log](https://github.com/Donkie/Spoolman/files/13199292/moonraker.log)

**Comment by rufinus** [comment]
thats sounds like the http daemon part of spoolman is crashing. i checked my instance (uses docker) if the container also crashes (but because of my config) gets restarted immediately - but this is not the case, had at least 5 prints today and spoolman container is up since 2 days.

**Comment by lorangthierry** [comment]
It looks like the process is sleeping. Mainsail says not ending initializing. If i jump to the shell to view the spoolman log comes a Starting Spoolman and then Mainsail works ... 

2023-11-03 13:22:40:INFO:Client 192.168.0.18 has stopped listening on pool spool
2023-11-03 17:21:38:INFO:Starting Spoolman v0.13.1 (commit: None) (built: None)
2023-11-03 17:21:38:INFO:Setting up database...
2023-11-03 17:21:38:INFO:No database type specified, using a default SQLite database located at "/home/pi/.local/share/spoolman/spoolman.db"
2023-11-03 17:21:38:INFO:Performing migrations...
2023-11-03 17:21:40:INFO:Scheduling automatic database backup for midnight.
2023-11-03 17:21:40:INFO:Startup complete.
2023-11-03 17:21:53:DEBUG:executing <function connect.<locals>.connector at 0x7fb8da68b0>

**Comment by killboxalpha** [comment]
I get the same thing in my spoolman logs. seems to happen every 2 hours for me. I lose spoolman and it kicks mainsail.

**Comment by lorangthierry** [comment]
> I get the same thing in my spoolman logs. seems to happen every 2 hours for me. I lose spoolman and it kicks mainsail.

How did you start the service? I changed it from `systemctl --user start Spoolman` to` systemctl start Spoolman`. 
Since that change it works. 

Moved Spoolman.service from /home/pi/.config/systemd/user/ to /etc/systemd/system/Spoolman.service
added User and Group

/etc/systemd/system/Spoolman.service

[Unit]
Description=Spoolman

[Service]
Type=simple
ExecStart=/home/pi/Spoolman-0.13.1/scripts/start.sh
WorkingDirectory=/home/pi/Spoolman-0.13.1
**User=pi
Group=pi**
Restart=always

[Install]
WantedBy=default.target

`sudo systemctl daemon-reload`
`sudo systemctl enable Spoolman`
`sudo systemctl start Spoolman`

**Comment by killboxalpha** [comment]
not sure how to move the spoolman service. I'm pretty much a simple user with this stuff.

**Comment by lorangthierry** [comment]
here the commands i used to move and start the service 
`systemctl --user stop Spoolman`
`systemctl --user disable Spoolman`
`sudo su `
`cd /home/pi/.config/systemd/user/`
`mv Spoolman.service /etc/systemd/system/`
`nano /etc/systemd/system/Spoolman.service`
-> added unter [Service]
User=pi
Group=pi
`systemctl deamon-reload`
`systemctl enable Spoolman`
`systemctl start Spoolman`
`ps -axu |grep spoolman`
-> pi        246703  0.3  1.9 686968 72340 ?        Sl   15:55   1:28 /home/pi/Spoolman-0.13.1/.venv/bin/python /home/pi/Spoolman-0.13.1/.venv/bin/uvicorn spoolman.main:app --host 0.0.0.0 --port 7912

**Comment by austinrdennis** [comment]
> here the commands i used to move and start the service `systemctl --user stop Spoolman` `systemctl --user disable Spoolman` `sudo su ` `cd /home/pi/.config/systemd/user/` `mv Spoolman.service /etc/systemd/system/` `nano /etc/systemd/system/Spoolman.service` -> added unter [Service] User=pi Group=pi `systemctl daemon-reload` `systemctl enable Spoolman` `systemctl start Spoolman` `ps -axu |grep spoolman` -> pi 246703 0.3 1.9 686968 72340 ? Sl 15:55 1:28 /home/pi/Spoolman-0.13.1/.venv/bin/python /home/pi/Spoolman-0.13.1/.venv/bin/uvicorn spoolman.main:app --host 0.0.0.0 --port 7912

This sorted the issue out completely. Added the bonus effect that it autostarts on reboot. THanks a million, this should be how the install script does it going forward imho.

**Comment by Donkie** [comment]
Yeah seems like it was a mistake to make Spoolman a user-level systemd service instead of a proper system-level one. I will update the script to do that instead.

**Comment by cruzer619** [comment]
this also fixed my issue.. but now my data isn't showing... didn't think this would point to a new location.. would it have?
