### ISSUE TITLE
Is there a SQL-Script for mySQL existing?

### ISSUE THREAD

**Issue by FOLeader** [Donkie/Spoolman#177]
I have 3 printers and i want to use one database for all spools.
mySQL is installed on a Windows PC, spoolman on RPI.
.env is created:

# DB Type: sqlite, mysql, postgresql, cockroachdb
# Default if not set: sqlite
SPOOLMAN_DB_TYPE=mysql

# DB Setup, if not using sqlite
SPOOLMAN_DB_HOST=192.168.1.xx
SPOOLMAN_DB_PORT=3306
SPOOLMAN_DB_NAME=spoolman
SPOOLMAN_DB_USERNAME=<user>
SPOOLMAN_DB_PASSWORD_FILE=
SPOOLMAN_DB_PASSWORD=<password>
SPOOLMAN_DB_QUERY=mysql

# Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
# Default if not set: INFO
SPOOLMAN_LOGGING_LEVEL=DEBUG

# Automatic nightly backup for SQLite databases
# Default if not set: TRUE
SPOOLMAN_AUTOMATIC_BACKUP=TRUE

# Host and port to listen on
SPOOLMAN_HOST=0.0.0.0
SPOOLMAN_PORT=7912

when i test the mysql client "mysql -u <user> -p -h 192.168.1.xx spoolman" it works fine.
But there is no table created during installation.
Is there a script existing for manually installation of tables and columns?

**Comment by Donkie** [comment]
The tables should be added automatically when spoolman starts. If they don't you have some connection issue. See the spoolman logs if you got any errors

**Comment by FOLeader** [comment]
where do i find the logs?

**Comment by Donkie** [comment]
Seems like it's crashing over and over. Try setting the LOGGING_LEVEL env variable to `debug` and see if you see any further errors

**Comment by FOLeader** [comment]
i have done, spoolman stopped, changed .env, spoolman started, same log entries
2023-10-29 10:48:46:INFO:Starting Spoolman v0.13.1 (commit: None) (built: None)
2023-10-29 10:48:46:INFO:Setting up database...
2023-10-29 10:48:50:INFO:Starting Spoolman v0.13.1 (commit: None) (built: None)
2023-10-29 10:48:50:INFO:Setting up database...
2023-10-29 10:48:54:INFO:Starting Spoolman v0.13.1 (commit: None) (built: None)
2023-10-29 10:48:54:INFO:Setting up database...
2023-10-29 10:48:58:INFO:Starting Spoolman v0.13.1 (commit: None) (built: None)
2023-10-29 10:48:58:INFO:Setting up database...
2023-10-29 10:49:02:INFO:Starting Spoolman v0.13.1 (commit: None) (built: None)
2023-10-29 10:49:02:INFO:Setting up database...

**Comment by FOLeader** [comment]
I got it via daemon.log
It tells me : _ValueError: bad query field: 'mysql'_
What should I use for the query?

**Comment by Donkie** [comment]
Ah I didn't even notice you had that set. You should probably leave it empty if you don't know what it's for.
I also think you need to setup a user in your database and fill that in the USERNAME and PASSWORD env vars.

**Comment by FOLeader** [comment]
I have done, you can see at the beginning of this messages, I only blanked it to show the rest
The mySQL server is not running on the rpi but on a windows pc

**Comment by FOLeader** [comment]
now it created the database tables but the another error appeared:
Oct 29 15:25:37 raspberrypi start.sh[16602]: INFO:     Application startup complete.
Oct 29 15:25:37 raspberrypi start.sh[16602]: ERROR:    [Errno -2] Name or service not known

**Comment by FOLeader** [comment]
got it finally.
the entries must be commented, not only kept empty.
Hope it could help others too
Thank you very much for your time :)
