### ISSUE TITLE
[FeatureRequest] Link from Filaments to Spool list with set filter

### ISSUE THREAD

**Issue by rufinus** [Donkie/Spoolman#180]
If you are on the details page of a Filament a button which links to the Spool page with filters on this Filament would be really helpful.

Thinking this further - what about adding a list/table of all Spools to the bottom of the details filament page. Which in turn links each row to the spool detail page.

Would be really great to have this as an overview. Like I have 15 black rolls, 3 are loaded to printers, 10 are in storage, 2 are empty.
So i can skip my extra inventory system.

**Comment by Donkie** [comment]
The first part of your request is already implemented, and will be available in the next release. Is that sufficient?

**Comment by rufinus** [comment]
perfect! as long as i get an overview I'm happy :)
