### ISSUE TITLE
Spoolman wont run, at all

### ISSUE THREAD

**Issue by srbjessen** [Donkie/Spoolman#181]
Have tried installing "normally", in Docker, and the integration to Mainsail.
Only Docker version would run, but screwed up other features.

When attempting to start it says: 
./start.sh
Starting Spoolman...
[FileNotFoundError]: [Errno 2] No such file or directory:
'/home/biqu/spoolman/.venv/bin/uvicorn'
Add '-v' to see the detailed traceback

But the file is there... Do i need to chmod it or...?

Also, in the initial step after "pdm sync --prod", i get:
Cloning into 'Spoolman'...
remote: Enumerating objects: 3769, done.
remote: Counting objects: 100% (991/991), done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 3769 (delta 684), reused 860 (delta 649), pack-reused 2778
Receiving objects: 100% (3769/3769), 1.15 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (2517/2517), done.
created virtual environment CPython3.9.2.final.0-64 in 1265ms
  creator CPython3Posix(dest=/home/biqu/spoolman-env, clear=False, no_vcs_ignore                                          =False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle                                          , via=copy, app_data_dir=/home/biqu/.local/share/virtualenv)
    added seed packages: Mako==1.2.4, MarkupSafe==2.1.3, PyMySQL==1.1.0, Pygment                                          s==2.16.1, SQLAlchemy==2.0.20, aiomysql==0.2.0, aiosqlite==0.19.0, alembic==1.11                                          .3, anyio==3.7.1, asyncpg==0.28.0, blinker==1.6.3, cachecontrol==0.13.1, certifi                                          ==2023.7.22, charset_normalizer==3.3.1, click==8.1.7, distlib==0.3.7, exceptiong                                          roup==1.1.3, fastapi==0.103.0, filelock==3.13.0, findpython==0.4.0, greenlet==2.                                          0.2, h11==0.14.0, httptools==0.6.0, idna==3.4, importlib_metadata==6.8.0, instal                                          ler==0.7.0, markdown_it_py==3.0.0, mdurl==0.1.2, msgpack==1.0.7, packaging==23.2                                          , pdm==2.10.0, pip==20.3.4, pip==23.3.1, pkg_resources==0.0.0, platformdirs==3.1                                          0.0, psycopg2_binary==2.9.7, pydantic==1.10.12, pyproject_hooks==1.0.0, python_d                                          otenv==1.0.0, requests==2.31.0, requests_toolbelt==1.0.0, resolvelib==1.0.1, ric                                          h==13.6.0, scheduler==0.8.4, setuptools==44.1.1, setuptools==68.1.2, shellingham                                          ==1.5.4, sniffio==1.3.0, spoolman==0.13.1+editable, sqlalchemy_cockroachdb==2.0.                                          1, starlette==0.27.0, tomli==2.0.1, tomlkit==0.12.1, typeguard==4.0.0, typing_ex                                          tensions==4.6.3, unearth==0.12.1, urllib3==2.0.7, uvicorn==0.22.0, uvloop==0.17.                                          0, virtualenv==20.24.6, websockets==11.0.3, wheel==0.34.2, zipp==3.16.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,Pyt                                          honActivator,XonshActivator

`fatal: not a git repository (or any of the parent directories): .git`

Requirement already satisfied: pip in /home/biqu/spoolman-env/l

**Comment by Donkie** [comment]
What distro are you running?

**Comment by Donkie** [comment]
Looks like PDM is using `virtualenv` instead of `venv` like I expect it to. I haven't made the script support virtualenv so that could be the reason.

Please redo the standalone install instructions, first removing your existing Spoolman. Before you run the `install_debian.sh` script though, first run `pdm config venv.backend venv`, make sure it succeeds, then run in the `install_debian.sh` script.

**Comment by srbjessen** [comment]
Seems like it still does it?
![image](https://github.com/Donkie/Spoolman/assets/92088582/66aabc09-122d-4c21-be72-1aa053460952)

**Comment by srbjessen** [comment]
Installs like this, but no luck in accessing client, and Mainsail is stuck on Initializing:


biqu@BTT-CB1:~$ pdm config venv.backend venv
biqu@BTT-CB1:~$ cd Spoolman-0.13.1/
biqu@BTT-CB1:~/Spoolman-0.13.1$ bash ./scripts/install_debian.sh
Python 3.9 or later is installed (Current version: 3.9.2)
Updating pip...
Installing Spoolman backend and its dependencies using PDM...
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /home/biqu/Spoolman-0.13.1/.venv
Synchronizing working set with resolved packages: 31 to add, 0 to update, 0 to
remove

  ✔ Install setuptools 68.1.2 successful
  ✔ Install aiosqlite 0.19.0 successful
  ✔ Install aiomysql 0.2.0 successful
  ✔ Install anyio 3.7.1 successful
  ✔ Install click 8.1.7 successful
  ✔ Install exceptiongroup 1.1.3 successful
  ✔ Install alembic 1.11.3 successful
  ✔ Install h11 0.14.0 successful
  ✔ Install fastapi 0.103.0 successful
  ✔ Install idna 3.4 successful
  ✔ Install httptools 0.6.0 successful
  ✔ Install asyncpg 0.28.0 successful
  ✔ Install mako 1.2.4 successful
  ✔ Install platformdirs 3.10.0 successful
  ✔ Install markupsafe 2.1.3 successful
  ✔ Install greenlet 2.0.2 successful
  ✔ Install pymysql 1.1.0 successful
  ✔ Install scheduler 0.8.4 successful
  ✔ Install sniffio 1.3.0 successful
  ✔ Install pydantic 1.10.12 successful
  ✔ Install psycopg2-binary 2.9.7 successful
  ✔ Install sqlalchemy-cockroachdb 2.0.1 successful
  ✔ Install starlette 0.27.0 successful
  ✔ Install typeguard 4.0.0 successful
  ✔ Install typing-extensions 4.6.3 successful
  ✔ Install uvicorn 0.22.0 successful
  ✔ Install websockets 11.0.3 successful
  ✔ Install zipp 3.16.2 successful
  ✔ Install uvloop 0.17.0 successful
  ✔ Install sqlalchemy 2.0.20 successful
  ✔ Install importlib-metadata 6.8.0 successful
Installing the project as a package...
  ✔ Install spoolman 0.13.1 successful

🎉 All complete!

Downloading Spoolman web client v0.13.1...
.env file not found. Creating it...
Do you want to install Spoolman as a systemd service? This will automatically start Spoolman when your server starts. (y/n)
y
Spoolman systemd service has been installed and Spoolman is now starting.
Spoolman will soon be reachable at http://<server-ip>:7912
You can start/restart/stop the service by running e.g. 'systemctl --user stop Spoolman'
You can disable the service from starting automatically by running 'systemctl --user disable Spoolman'
You can view the Spoolman logs by running 'journalctl --user -u Spoolman'
Spoolman has been installed successfully!
If you want to connect to an external database, you can edit the .env file and restart the service.

**Comment by Donkie** [comment]
That's great, what does it say if you run

systemctl --user status Spoolman

?

**Comment by srbjessen** [comment]
biqu@BTT-CB1:~$ systemctl --user status Spoolman
● Spoolman.service - Spoolman
     Loaded: loaded (/home/biqu/.config/systemd/user/Spoolman.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-10-31 07:08:50 UTC; 47s ago
    Process: 2027 ExecStart=/home/biqu/Spoolman-0.13.1/scripts/start.sh (code=exited, status=203/EXEC)
   Main PID: 2027 (code=exited, status=203/EXEC)
        CPU: 3ms

Oct 31 07:08:50 BTT-CB1 systemd[1894]: Spoolman.service: Scheduled restart job, restart counter is at 5.
Oct 31 07:08:50 BTT-CB1 systemd[1894]: Stopped Spoolman.
Oct 31 07:08:50 BTT-CB1 systemd[1894]: Spoolman.service: Start request repeated too quickly.
Oct 31 07:08:50 BTT-CB1 systemd[1894]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 07:08:50 BTT-CB1 systemd[1894]: Failed to start Spoolman.

**Comment by srbjessen** [comment]
biqu@BTT-CB1:~$ journalctl --user -u Spoolman
-- Journal begins at Tue 2023-10-31 06:53:11 UTC, ends at Tue 2023-10-31 07:10:39 UTC. --
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Started Spoolman.
Oct 31 06:54:10 BTT-CB1 systemd[1232]: Spoolman.service: Failed to locate executable /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:10 BTT-CB1 systemd[1232]: Spoolman.service: Failed at step EXEC spawning /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Scheduled restart job, restart counter is at 1.
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Stopped Spoolman.
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Started Spoolman.
Oct 31 06:54:10 BTT-CB1 systemd[1296]: Spoolman.service: Failed to locate executable /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:10 BTT-CB1 systemd[1296]: Spoolman.service: Failed at step EXEC spawning /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Scheduled restart job, restart counter is at 2.
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Stopped Spoolman.
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Started Spoolman.
Oct 31 06:54:10 BTT-CB1 systemd[1352]: Spoolman.service: Failed to locate executable /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:10 BTT-CB1 systemd[1352]: Spoolman.service: Failed at step EXEC spawning /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 31 06:54:10 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Spoolman.service: Scheduled restart job, restart counter is at 3.
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Stopped Spoolman.
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Started Spoolman.
Oct 31 06:54:11 BTT-CB1 systemd[1357]: Spoolman.service: Failed to locate executable /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:11 BTT-CB1 systemd[1357]: Spoolman.service: Failed at step EXEC spawning /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Spoolman.service: Scheduled restart job, restart counter is at 4.
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Stopped Spoolman.
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Started Spoolman.
Oct 31 06:54:11 BTT-CB1 systemd[1361]: Spoolman.service: Failed to locate executable /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:11 BTT-CB1 systemd[1361]: Spoolman.service: Failed at step EXEC spawning /home/biqu/Spoolman/scripts/start.sh: No such file or directory
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 31 06:54:11 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 06:54:12 BTT-CB1 systemd[1195]: Spoolman.service: Scheduled restart job, restart counter is at 5.
Oct 31 06:54:12 BTT-CB1 systemd[1195]: Stopped Spoolman.
Oct 31 06:54:12 BTT-CB1 systemd[1195]: Spoolman.service: Start request repeated too quickly.
Oct 31 06:54:12 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 06:54:12 BTT-CB1 systemd[1195]: Failed to start Spoolman.
Oct 31 07:02:46 BTT-CB1 systemd[3510]: Spoolman.service: Failed to locate executable /home/biqu/Spoolman-0.13.1/scripts/start.sh: Permission denied
Oct 31 07:02:46 BTT-CB1 systemd[1195]: Started Spoolman.
Oct 31 07:02:46 BTT-CB1 systemd[3510]: Spoolman.service: Failed at step EXEC spawning /home/biqu/Spoolman-0.13.1/scripts/start.sh: Permission denied
Oct 31 07:02:46 BTT-CB1 systemd[1195]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 31 07:02:46 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 07:02:47 BTT-CB1 systemd[1195]: Spoolman.service: Scheduled restart job, restart counter is at 1.
Oct 31 07:02:47 BTT-CB1 systemd[1195]: Stopped Spoolman.
Oct 31 07:02:47 BTT-CB1 systemd[1195]: Started Spoolman.
Oct 31 07:02:47 BTT-CB1 systemd[3512]: Spoolman.service: Failed to locate executable /home/biqu/Spoolman-0.13.1/scripts/start.sh: Permission denied
Oct 31 07:02:47 BTT-CB1 systemd[3512]: Spoolman.service: Failed at step EXEC spawning /home/biqu/Spoolman-0.13.1/scripts/start.sh: Permission denied
Oct 31 07:02:47 BTT-CB1 systemd[1195]: Spoolman.service: Main process exited, code=exited, status=203/EXEC
Oct 31 07:02:47 BTT-CB1 systemd[1195]: Spoolman.service: Failed with result 'exit-code'.
Oct 31 07:02:47 BTT-CB1 systemd[1195]: Spoolman.service: Scheduled restart job, restart counter is at 2.
Oct 31 07:02:47 BTT-CB1 systemd[1195]: Stopped Spoolman.

**Comment by Donkie** [comment]
Ok, looks like the start script doesn't have proper permissions.

Run `chmod +x start.sh` when you have cd into the scripts dir.

**Comment by srbjessen** [comment]
IT WORKS!!!!!

Thank you sooo much for quick assistance.
Can't wait to get started.

Will make sure to sponsor your hard work.

**Comment by Donkie** [comment]
Nice, no problem :)
