### ISSUE TITLE
Can't update, getting error on install_debian

### ISSUE THREAD

**Issue by Eka157** [Donkie/Spoolman#182]
so I followed the directions on the readme for updating the standalone, deleted, reclone git and then run install_debian again. I get this when I attempt that, now I cannot delete spoolman folder (in main directory) at all:

v2.4183@VORON:~/Spoolman $ bash ./scripts/install_debian.sh
Python 3.9 or later is installed (Current version: 3.9.2)
Updating pip...
Installing Spoolman backend and its dependencies using PDM...
python.use_venv is on, creating a virtualenv for this project...
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: argument dest: the destination . is not write-able at /home/v2.4183/Spoolman
[VirtualenvCreateError]: Command '['/usr/bin/python3', '-m', 'virtualenv', '/home/v2.4183/Spoolman/.venv', '-p', '/usr/bin/python', '--prompt=spoolman-3.9', 
'--no-pip', '--no-setuptools', '--no-wheel']' returned non-zero exit status 2.

**Comment by Eka157** [comment]
got it working again with command

sudo rm -r Spoolman 
git clone Spoolman

**Comment by Donkie** [comment]
So the issue is fixed? :)
