### ISSUE TITLE
How to change current spool with the Rest API

### ISSUE THREAD

**Issue by TheBest6337** [Donkie/Spoolman#183]
Hello, I want to change the current spool, with the rest api, but the documentations arent helping me.

**Comment by TheBest6337** [comment]
I'm using mainsail. My goal is to have a NFC chip on the spool that runs a script on my phone which then does the REST request.

**Comment by clevelandcs** [comment]
@TheBest6337 There isn't any concept of "current spool" with the Spoolman REST API. Current spool is in the context of the Moonraker API instance for each printer. You'll want to look at the Moonraker API [documentation](https://moonraker.readthedocs.io/en/latest/web_api/#spoolman-apis) for how to set the currently selected spool or possibly look at getting code merged to Moonraker to add NFC as core functionality of the Spoolman integration for Moonraker. I'd love to see that kind of integration added so definitely keep me in the loop how it goes for you. Maybe you could start a Discussion topic on either repository around your work?
