### ISSUE TITLE
Spool ID not Showing when changing spool

### ISSUE THREAD

**Issue by Ohara2208** [Donkie/Spoolman#186]
When I select to change spool the list of avaible spools is shown but there is no way to difrenciate similar rolls. 
Spool ID needs to be shown on this screen. As you can see below spool ID no. 6 is active

![image](https://github.com/Donkie/Spoolman/assets/149898595/aa96b83e-d5ad-4535-8910-c69d22cba94d)

**Comment by Donkie** [comment]
This is a mainsail issue, not Spoolman.
Besides, I think it's already fixed and should be available in the next release of Mainsail.

**Comment by Ohara2208** [comment]
@Donkie Still not fixed on latest Mainsail update Fyi 
Is this part done by Mainsail Devs?
