### ISSUE TITLE
Database lost on Unraid docker

### ISSUE THREAD

**Issue by Lecso11** [Donkie/Spoolman#188]
I run my Spoolman docker on my Unraid server, and when I updated the the docker, all of my data went lost. 
The appdata/spoolman folder is empty. Is this an issue with the docker not finding my old database, or is my database lost? If it is lost, how could I prevent it to happen again?

**Comment by ThomasHineXYZ** [comment]
Correct.

Unless it was put in a persistent storage or external database, then the data is gone.

**Comment by Donkie** [comment]
I have now put in place two measures for the next release to help reduce this issue in the future:

1. Spoolman will now crash with a helpful error if it doesn't have permissions to write to the data dir
2. A big warning will appear in the logs if you haven't mounted the data dir correctly
