### ISSUE TITLE
Feature request: "rewind" feature for when you accidentally had the wrong spool selected

### ISSUE THREAD

**Issue by Aasikki** [Donkie/Spoolman#189]
Would be nice to have a feature transfer recently used filament filament from one spool to another, in the case a wrong spool was accidentally selected. It's not too bad to fix it manually right now but it would be nice to be able to just do it with a click of a button. Rewind would be a nice name for this feature I think. ⏪🧵

Got the idea for this, unsurprisingly, by accidentally having the wrong spool selected lol.

**Comment by Donkie** [comment]
I think doing exactly what you want here is a too specific use-case to warrant its own feature. However, it's planned to implement a button that lets you easily add/subtract filament from a roll instead of having to edit the absolute weight. #30

**Comment by Aasikki** [comment]
> I think doing exactly what you want here is a too specific use-case to warrant its own feature. However, it's planned to implement a button that lets you easily add/subtract filament from a roll instead of having to edit the absolute weight. #30

That would also help a lot!
