### ISSUE TITLE
Mainsail Active Spool Not setting

### ISSUE THREAD

**Issue by solo2424** [Donkie/Spoolman#19]
I don't beleive that the active spool is not changing in mainsail anymore. I set to a couple different spools but my used weight are not changing. Is there a way to see what spool is set to active?

**Comment by locki-cz** [comment]
something like show spool info will be great!

**Comment by Donkie** [comment]
Yes, this is an easy addition to Moonraker. I will add it this weekend.

**Comment by Donkie** [comment]
Best way to do that for now is by just putting `http://192.168.0.123:7125/server/spoolman/spool_id` (where the ip:port is your Moonraker address) in your browser. That will tell you the currently active spool ID. Unfortunately, making an equivalent gcode command like for setting a spool ID isn't as easy as I thought.

**Comment by Donkie** [comment]
Closing since this is solved
