### ISSUE TITLE
SSL force in locally hosted Spoolman QR code scanner

### ISSUE THREAD

**Issue by fryc88** [Donkie/Spoolman#196]
Hi, 
Is there any specific reason why I'm unable to use QR scanner in self hosted, on my own, local server in forced SSL mode? Container don't have access to internet, there's absolutely (in my case) no need for SSL except for extra hassle, but I'm unable to use it.
Is there any switch to add to docker compose to turn off that requirement or something, or I really have to create certs, etc. just to access it locally?

![IMG_7789](https://github.com/Donkie/Spoolman/assets/50572708/f8bb6256-853e-46c5-ba80-9e112dc59fc3)

**Comment by mkevenaar** [comment]
Hi, this is not a limitation of Spoolman, but from the browser itself. Unfortunately, there is nothing that can be done to solve this.

**Comment by fryc88** [comment]
Ok it sounds a bit odd, I'm using tens of for example home assistant stuff that work only locally in docker and these don't require SSL, so saying it's browsers requirement sounds a bit odd, unless there's some specific component that requires it...

**Comment by mkevenaar** [comment]
Accessing a camera and microphone is limited to HTTPS only. See: https://blog.mozilla.org/webrtc/camera-microphone-require-https-in-firefox-68/
