### ISSUE TITLE
Spoolman restart necessary after a while to connect to mainsail

### ISSUE THREAD

**Issue by Seqway** [Donkie/Spoolman#199]
Hello,
when I switch off my printer but my clipper host is still available I am facing problems that after a while I can't connect to mainsail.

I figured out that I need to restart the spoolman service (systemctl --user restart Spoolman) and after that I immediately can connect to mainsail.
Can you please check this if it is a bug ?

**Comment by cief1k76** [comment]
> Hello, when I switch off my printer but my clipper host is still available I am facing problems that after a while I can't connect to mainsail.
> 
> I figured out that I need to restart the spoolman service (systemctl --user restart Spoolman) and after that I immediately can connect to mainsail. Can you please check this if it is a bug ?

Same for me

**Comment by Seqway** [comment]
> > Hello, when I switch off my printer but my clipper host is still available I am facing problems that after a while I can't connect to mainsail.
> > I figured out that I need to restart the spoolman service (systemctl --user restart Spoolman) and after that I immediately can connect to mainsail. Can you please check this if it is a bug ?
> 
> Same for me i found this [#176 (comment)](https://github.com/Donkie/Spoolman/issues/176#issuecomment-1793567312)
> 
> maybe a solution

Yes I followed the instructions in this #176 comment and yes it seems now to work.
No need ow for restart up to now. Seems to work. I will check on long term also.
