### ISSUE TITLE
Multiple printers same PC not working. 

### ISSUE THREAD

**Issue by solo2424** [Donkie/Spoolman#21]
I am trying to run Spoolman on two instants of moonraker on the same machine. They are separated by ports. One is port 7125 and the other 7126. They each have their own moonraker config in the following folders (7125 in RedRover_data/config and 7126 in WhiteLighting_data/config).

The version that has been working and still is, is 7126. When I change the active spool, in that machine, it works no problem. But when I try on the 7125 (RedRover) printer. Nothing happens. I have both moonraker.conf with the following. 

[spoolman]
server: http://192.168.0.93:7912

I also try setting it manually with the curl commands but both old and new commands do not work for either machine. See txt file for details.   
[spoolman commands with errors.txt](https://github.com/Donkie/Spoolman/files/11918598/spoolman.commands.with.errors.txt)

**Comment by Donkie** [comment]
The curl command has changed recently. You need to add /server before /spoolman in the URL.

See if that works.

**Comment by solo2424** [comment]
Yup, that works for WhiteLighting (7126) but not for RedRover (7125). Which makes sense, since that is what I am experincing when I set in mainsail.

**Comment by solo2424** [comment]
[moonraker (3).log](https://github.com/Donkie/Spoolman/files/11919047/moonraker.3.log)
 
It doesn't look like moonraker is recording anything for that command. I ran the command multiple times but I am not seeing any entry in the log.
![image](https://github.com/Donkie/Spoolman/assets/1903450/316428ac-56f7-439f-b935-eefeb96d30d9)

**Comment by Donkie** [comment]
Are you sure your moonraker is updated properly? POST /server/spoolman/spool_id should not be a 404 if you run the latest.

**Comment by solo2424** [comment]
Yea, I don't think the WhiteLighting printer would work if I wasn't. But I did confirm.

solo@SoLoServer:~/moonraker$ git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
solo@SoLoServer:~/moonraker$

**Comment by Donkie** [comment]
You may be tricked that it is up to date if you're on the wrong branch. Do a `git checkout master` then `git pull` again. After that, in the update manager in Mainsail, you should see the following version:

![image](https://github.com/Donkie/Spoolman/assets/2332094/295f0ad9-5ab2-4dcc-a2de-f3801335de51)

**Comment by solo2424** [comment]
I confirmed that I am on the correct version that you took the screenshot
of and I also did the get checkout branch and get pull still says I was up
to date.

I have a print going now but when it finishes I will reboot the server.

I also went to the web browser to check the active pool like you suggested
in the other thread and it works for my white lightning but not for this
one we're having issues with. I get the 404 error

**Comment by Donkie** [comment]
Maybe a restart is what's necessary then, keep me updated :)

**Comment by solo2424** [comment]
Reboot did it. thanks again!

**Comment by Donkie** [comment]
Great, no problem!
