### ISSUE TITLE
[ProjectError]: Lock file does not exist, nothing to install

### ISSUE THREAD

**Issue by Travis90x** [Donkie/Spoolman#210]
![immagine](https://github.com/Donkie/Spoolman/assets/23300077/58a00864-5ac1-4646-8045-40edfe3a6492)

**Comment by Donkie** [comment]
Try cd-ing into the Spoolman folder and running `bash scripts/install_debian.sh` instead

**Comment by Travis90x** [comment]
The Script is not optimized while update, please write a better automatic installation script to avoid interruption.

![immagine](https://github.com/Donkie/Spoolman/assets/23300077/7c6b770c-bc30-43ad-9c49-ff68fbfd931e)
