### ISSUE TITLE
Feature Request: more Fields about Filament Data/pdf Datasheet upload

### ISSUE THREAD

**Issue by Lala1969** [Donkie/Spoolman#220]
Hello,
I like Spoolman its where I can have all Information about my Filaments.
I would like to add Filament Datasheet for the Filament in Spoolman.

Exsample: https://www.extrudr.com/filerpool/download/datei/752/

Thank you for doing so great

**Comment by rufinus** [comment]
then do?

![image](https://github.com/Donkie/Spoolman/assets/343160/1ce633c3-c913-499f-ac46-acc76c92241f)

**Comment by Lala1969** [comment]
Thank you. its a nice workout to store the link..I would like to tore the pdf.... but this helps.
Thank u

**Comment by Donkie** [comment]
Storing files is not something I'd rather dive into as it can open up a whole can of worms regarding security risks etc. I think it's best if this is solved as @rufinus said, input a link instead. If you need to upload the PDF somewhere, then you should setup a dedicated file host service for that and upload the PDFs there. You can very easily setup a service like https://github.com/timvisee/send to host images locally.

**Comment by Donkie** [comment]
I have now added the ability to make custom extra fields. Please test it out in the beta for me before I make a release. See #283 for more information.
