### ISSUE TITLE
Danish translation not showing.

### ISSUE THREAD

**Issue by srbjessen** [Donkie/Spoolman#228]
Very minor "bug"
Danish translation added in changelog, but not available in language menu on V0.14.0

Keep up the good work

**Comment by Donkie** [comment]
Yes, mistake from my side. It was fixed just after the release, so it will be in in the next one.

https://github.com/Donkie/Spoolman/commit/cf417845e9203e2bdea8780165c6a86ff9743a3d

**Comment by srbjessen** [comment]
Hate to be that guy. 
Still no danish in 0.15.0 :-D
