### ISSUE TITLE
Show filament color box in list

### ISSUE THREAD

**Issue by Donkie** [Donkie/Spoolman#23]
Something like how it's in Octoprint:
![image](https://github.com/Donkie/Spoolman/assets/2332094/de9faa49-2802-4318-9ae2-8c7b3aa426e3)

From #14

**Comment by solo2424** [comment]
I see that it says you completed this but I am not seeing it. I stopped the docker, did a pull and restarted but I am not seeing the color boxes. Am I missing something?

**Comment by Donkie** [comment]
It's coming in next release 😉
