### ISSUE TITLE
Python 3.7 needed

### ISSUE THREAD

**Issue by michael2608H** [Donkie/Spoolman#230]
Hi, 
Elegoo released the Neptune 4 Printers which run on Klipper, but use an old Python Version (3.5).
Your nice Tool runs requests at least 3.7 - Updating the printer is not an option as no one knows if it still will run afterwards.
Is there any chance the reduce the requirements in the tool ?
thx

**Comment by rufinus** [comment]
no one said spoolman needs to run on the printer itself.

PYthon 3.5 is EOL since 09-2020 - even Python 3.7 is EOL since 06.2023.

**Comment by Donkie** [comment]
Yup, what @rufinus said. There is no way I'm downgrading the Python version to 3.5, it's too old. You have to host Spoolman on some other machine.

**Comment by michael2608H** [comment]
Sure I know. On my last printer I mwas using octopi on a raspi 3. On the ender i am not able as I don't get the MCU address. Ls is not working. So no external device. The only possible is to install on the printer itself. In addition elegoo does not support any update of python. So I am trapped in a loop.

**Comment by duerk-de** [comment]
A year later Python 3.9 is required:
> Current version of Python (3.8.10) is too old for Spoolman.
Which features require this version and do not work with an older version?

@Donkie Why are you writing about downgrading? The only point is not to exclude old systems!

**Comment by Donkie** [comment]
Newer python versions brings many features that improve the library compatibility, performance, and development experience.

You have to remember that this project is something I do in my free time, and it's always a trade off between maximizing compatibility and efficiency. Using older Python versions could mean I can't use all the libraries I today depend on for example, which means I would need to code them myself. Older Python versions also has less of the nice syntax features that newer Python has, e.g. type hinting.
