### ISSUE TITLE
Toolchanger/MMU support

### ISSUE THREAD

**Issue by Marshalldog** [Donkie/Spoolman#239]
**Is your feature request related to a problem? Please describe.**
Currently building a 2.4 with a tapchanger. I'd like to be able to assign each extruder a different filament so that Spoolman can track both spools independently.
Concept:
So where for the interface here's a mockup:
![Untitled](https://github.com/Donkie/Spoolman/assets/99470771/0506e908-5c8f-461d-a146-636968cc377a)
So each extruder can be assigned a different filament

**Comment by Donkie** [comment]
Spoolman has full support for this already. It is something that needs to be added to Moonraker/the  frontends instead.
