### ISSUE TITLE
Can't see Spoolman integration on fluidd

### ISSUE THREAD

**Issue by lulu0125** [Donkie/Spoolman#241]
![image](https://github.com/Donkie/Spoolman/assets/155187247/941df49f-0a6e-43db-9132-b961325daf79)
![image](https://github.com/Donkie/Spoolman/assets/155187247/37292e4e-c9d0-4f5a-96b4-7e3e07e24bf5)
(don't worry about the 9912 port it's the correct port)
[moonraker (6).log](https://github.com/Donkie/Spoolman/files/13799879/moonraker.6.log)

**Comment by rufinus** [comment]
which moonraker version are u using?

it seems more like your moonraker version is too old and doesnt know of the [spoolman config block.

showing screenshots with error message not in englisch doesnt help with regards of helping you.

**Comment by Ladin69** [comment]
```
[spoolman]
server: http://192.168.0.20:7912  ( link to yours Spool Manger )
#   URL to the Spoolman instance. This parameter must be provided.
# sync_rate: 5
#   The interval, in seconds, between sync requests with the
#   Spoolman server.  The default is 5.
```
