### ISSUE TITLE
Userdefined Custom Fields

### ISSUE THREAD

**Issue by rufinus** [Donkie/Spoolman#242]
As there are multiple szenarious and different use cases, I think the proper long time solution would be to allow custom user fields.
This would allow each installation only have the fields they really need, and we dont get a bunch of fields when they are not needed. It will also reduce the number of feature requests regarding fields in the long run.

Settingspage - allow of adding, renaming and removing of custom fields.
Each custom fields has this form fields:
 - name
 - type
   - int
   - float
   - bool
   - text
   - textarea
   - (choice)
 - area (one of filament, spool or vendor) 
 - showInList (bool/checkbox)
 - isRequired (bool/checkbox)

the type is only used for display - the database field type is always a text field. choice would need an additional field where the options can be entered (like comma sperated list) rendering would then be a select. (or even allow_multiple setting and render as either multiselect or checkbox group. - but this is a bit more work then the "normal" options - and i think not required for the first iteration.)

URL's in text/textarea fields are automaticly detected an rewritten to a href links. (like it is in the comment field)

when render the form of the area the field depends on the type. (like type number, text, checkbox, and so on)

refs: 
 - #239
 - #238 
 - #235 
 - #200 
 - #191 
 - #129 
 - #220 
 - (please extend if i missed any)

I think the database schema for it is rather straight forward.

**Comment by Donkie** [comment]
Thanks, this is exactly something I have been planning in my head as well. I think it would be good if we also combine this with a centralized database of common options, otherwise it can be difficult for thirdparty tools to integrate with the custom fields if everyone names things differently.

**Comment by Donkie** [comment]
I have now added the ability to make custom extra fields. Please test it out in the beta for me before I make a release. See #283 for more information.
