### ISSUE TITLE
Entry of temperature ranges / drying data / URL field

### ISSUE THREAD

**Issue by Tuxtom007** [Donkie/Spoolman#243]
Hello,

I just discovered Spoolman today and immediately installed and tested it. I have already noticed a few things that are not quite so good and that I would like to see changed:

- It is not possible to specify a temperature range for the nozzle and heating bed temperature, e.g. 
240 - 270 °C
No matter in which format I enter it, it always comes out like this:
240.270 °C

- Furthermore, it would be nice if there was an extra field for necessary drying settings, which are necessary for some filament types, e.g:
Drying required: yes/no
Drying time: 8 h
Drying temperature: 70°C

- URL field(s)
I would still like to have fields for URLs, e.g. to the manufacturer's page of the filament and to the respective data sheet

Thanks in advance and many thanks for the tool

**Comment by rufinus** [comment]
url fields - just use the url in the comment field - its converted to a link automaticly.

for the other fields see #242

**Comment by Tuxtom007** [comment]
Great,  thanks
