### ISSUE TITLE
Spool Sets Status Tab

### ISSUE THREAD

**Issue by Ktmdude88** [Donkie/Spoolman#25]
Not sure if a idea was already planned for this or status in general. 

Please add separate tab to show which printer or instance ip/port currently has "set" a spool and which one it is set on. 

This can be used to verify the printer is set to a spool and the correct one without flipping between printer instances.

**Comment by Donkie** [comment]
Spoolman currently has no information on what printers are "using" a spool. It is a property of the printer, not Spoolman.

However, as mentioned in other discussions, I'm contemplating adding a Printers section to Spoolman, where Spoolman would then instead be in charge of spool assignment. This would be an optional feature.

**Comment by Ktmdude88** [comment]
Thanks for rapid response.
 I was assuming as information was sent to spoolman it would also be able to pass along a tag from moonraker.

Not sure for multiple printer instances having spoolman assign the spools would work correct if it wouldn't know what printer is sending the usage? 

Sorry pretty green in the database and python but stoked on this project. Have had it up and running for several pushes now no issues 👍

**Comment by Donkie** [comment]
Closing this as this will be tracked in #26
