### ISSUE TITLE
Moonraker updater broken for spoolman

### ISSUE THREAD

**Issue by Marshalldog** [Donkie/Spoolman#255]
**Describe the bug**
I can't get the moonraker manager to work with Spoolman.
![Screenshot 2024-01-07 0132](https://github.com/Donkie/Spoolman/assets/99470771/75975b3a-f700-4742-946b-ae46ee51b039)

My setup:
used guide: https://www.youtube.com/watch?v=hRjlJ8aPaOY&t=192s
File Path: /home/pi/spoolman
![Screenshot 2024-01-07 000920](https://github.com/Donkie/Spoolman/assets/99470771/ad82c30b-39d0-428c-ae3a-ce11938217ed)

Donkie suggested:
```
[update_manager spoolman]
type: web
channel: stable
repo: Donkie/Spoolman
path: ~/Spoolman
```
I altered mine to the following cause it caused an issue (I didn't use a capital letter in my folder name):
```
[update_manager spoolman]
type: web
channel: stable
repo: Donkie/Spoolman
path: ~/spoolman
```

All of that results in this output:
![Screenshot 2024-01-07 000132](https://github.com/Donkie/Spoolman/assets/99470771/79004882-2e95-40fc-9421-35b51f4aae78)

Hardware + Software info
hardware: pi 4
OS: raspbian 
spoolman: 0.15.0
![Screenshot 2024-01-07 000132](https://github.com/Donkie/Spoolman/assets/99470771/a7ddf58b-b672-47f7-8511-8d23ba493ea6)

**Comment by Marshalldog** [comment]
Found in moonraker log
```
2024-01-07 00:01:01,657 [base_deploy.py:log_info()] - Web Client spoolman: Invalid Web Installation, aborting remote refresh
2024-01-07 00:01:01,657 [web_deploy.py:_log_client_info()] - Web Client spoolman Detected:
Repo: Donkie/Spoolman
Channel: stable
Path: /home/pi/spoolman
Local Version: ?
Remote Version: ?
Valid: False
Fallback Client Detected: False
Pre-release: False
Download Url: ?
Download Size: 0
Content Type: ?
Rollback Version: ?
Rollback Repo: ?
```

**Comment by Donkie** [comment]
It's probably due to the fact that the updater only works if your current spoolman version is at least 0.15.0. You need to manually install that like before. Any future updates however, should be compatible.

**Comment by Marshalldog** [comment]
I did before i even attempted any of this
![Screenshot 2024-01-07 102716](https://github.com/Donkie/Spoolman/assets/99470771/9eb3f46b-549a-4c82-8b95-8931f553935c)

**Comment by Marshalldog** [comment]
the up to date check just says invalid

**Comment by stephbellemare** [comment]
Same issue here. exactly same.

**Comment by stephbellemare** [comment]
Fixed the issue - update_manager does not work if you install with Docker. You need to remove the container and install as standalone. then it will all work.
