### ISSUE TITLE
Moonraker timeout error

### ISSUE THREAD

**Issue by ksummers92** [Donkie/Spoolman#264]
[moonraker 2.log](https://github.com/Donkie/Spoolman/files/13931521/moonraker.2.log)
Moonraker is reporting an error connecting to spoolman during print. The only steps that seem to reproduce the error is to select a spool prior to the print and start the print. The error occurs sometime during the print. I am using Happy-Hare with a Tradrack MMU that has some spoolman integration, but this occurs with single color prints also.

**Comment by ksummers92** [comment]
It is possible that this is a moonraker issue.
![image](https://github.com/Donkie/Spoolman/assets/66363414/76cf877e-4922-4e70-bb5b-8c188594e8bc)

**Comment by Arksine** [comment]
This should be partially resolved, see [Arksine/moonraker/#792](https://github.com/Arksine/moonraker/pull/792).  Mainsail will have a resolution on its side soon.

**Comment by ksummers92** [comment]
I just saw the update. Reinstalled spoolman and am testing now. Thank you!
