### ISSUE TITLE
[Minor] Filament filter selector contains duplicate entries when multiple materials defined

### ISSUE THREAD

**Issue by hcooper** [Donkie/Spoolman#276]
When filtering by filament it lists duplicate entries (one entry for each material type). The expectation of when filtering by a given filament would be to see all those filaments (unless there was a filter also applied to the material column separately). I think a screenshot shows the issue clearly (Overture White):

![image](https://github.com/Donkie/Spoolman/assets/131580/175654f8-ce44-4d20-9215-625b94699801)

**Comment by rufinus** [comment]
its indendent. the filament has a material type, so to filter spools by filament it has to show it - there is no way to seperate it - from a database point of view its an own entry the only thing which is the same is the name.

Its the same "problem" if you have the same filaments on different spool sizes. see #191 for a solution with more info in a tooltip. maybe this tooltip has to be included in the filters too.

**Comment by Donkie** [comment]
I'm confused, why do you have multiple filament objects of same brand and color?

**Comment by rufinus** [comment]
> I'm confused, why do you have multiple filament objects of same brand and color?

My guess is different Material. (but as noted applies to spoolsizes too)

**Comment by Donkie** [comment]
Oh of course, I mixed up material and color in my head for some reason. Yeah this makes sense that it's an issue.
