### ISSUE TITLE
Multi Material Support

### ISSUE THREAD

**Issue by napalmz** [Donkie/Spoolman#277]
**Is your feature request related to a problem? Please describe.**
When you start a print job (From Mainsail, for example) the spool loaded on Spoolman is shown. If the print includes more than one material/color, it is not possible to associate multiple active spools. This way, when changing filament, it will continue to unload weight from the wrong spool.

**Describe the solution you'd like**
When printing is launched, it must be possible to associate the correct spools with each filament being printed, changing at the color/material change the active spool into which to discharge the quantity being printed. Both in prints with automatic color change (ERCF, MMU, TradRack, etc.) and those with manual change.

**Describe alternatives you've considered**
For the case of manual filament changing only, give the option of changing the active spool from the Mainsail/KlipperScreen interface (unless this is already possible).

**Additional context**
Currently from Mainsail you can see if a print is multimaterial/multicolor from the "Filament name" and "Filament Type" columns. However, there does not appear to be a distinction on totals quantities. It may be necessary to make a change to the slicer to indicate, when changing filaments, a command that selects the number of spool that becomes active, assuming a progressive numbering (0, 1, 2, etc.) to be matched between slicer and spoolman when the print is launched.
This is similar to what happens at print launch in AMS/AMS Lite-equipped printers.

**Comment by Donkie** [comment]
Spoolman fully supports multiple parallel spools. This is something that must be implemented in your frontend like Mainsail, and/or Moonraker

**Comment by napalmz** [comment]
So I've to talk to Mainsail dev team. Thank you!
