### ISSUE TITLE
Add images to https://hub.docker.com/

### ISSUE THREAD

**Issue by SellA** [Donkie/Spoolman#28]
Hi,
i really would like to thank you for your work! Spoolman is really something i would like to have for a long time. I've installed it on my Synology NAS using command line from SSH. However, if you add images to https://hub.docker.com/ it would be easier for everyone to keep it updated from the UI instead of SSH into the NAS everytime.
I tried to add also the ghcr.io/donkie url to repositories list but it doesn't work. Sorry but i'm not so experienced with docker. If there is already a solution please let me know.

Michele

**Comment by Donkie** [comment]
I haven't used Synology NAS myself but adding ghcr.io as a custom registry should be possible. Can you show me how you tried configuring it?

**Comment by SellA** [comment]
So i've tried searching online and found this: https://stackoverflow.com/questions/73825556/adding-ghcr-github-docker-regustry-to-synology-docker-results-in-registry-ret

It seems that you are right. It should work but it isn't! For now i will stick wih issuing sudo docker-compose pull from SSH.
If you could add images also to the default hub of Synology Docker version, it would be nice.

**Comment by Donkie** [comment]
Keeping images in multiple locations is always a hassle, so I'd prefer not to do it. But if enough people have this issue then I'll reconsider.

The issues I'm seeing regarding Synology and ghcr.io is that the token authentication is not supported, but since this is a public image (no login required) I don't see why that would be an issue..

**Comment by SellA** [comment]
Yeah i see but i can't find any solution and i'm not skilled enough to track this down.
I've managed to pull the image by using Portainer. That is enough for me because it removes the hassle of ssh'ing into the NAS everytime.
Thank for you to watching into it. I think we can close this.

**Comment by cuiviemen** [comment]
I would like to second this. It is real hassle to ssh to the synology NAS just to pull the latest image and restart the docker image. Especially when watchtower can do this for me automatically.
