### ISSUE TITLE
[UI] Create spool from the filament page

### ISSUE THREAD

**Issue by hcooper** [Donkie/Spoolman#281]
From the filaments page it would be nice to quickly create a spool by using either the click-menu or the actions column.

**Comment by hcooper** [comment]
2 second mock-up of the idea...

![image](https://github.com/Donkie/Spoolman/assets/131580/7ac1d6b4-4c6b-4d6a-af0b-fcc6e7f712a8)

**Comment by Donkie** [comment]
Good idea :)
