### ISSUE TITLE
QR Code scanner error(not HTTPS)

### ISSUE THREAD

**Issue by ramaxa9** [Donkie/Spoolman#285]
**Describe the bug**
i got an error with qr code scanner
"an unknown error occurred (OverconstrainedError)"

**Screenshots**
![Screenshot_20240126_101907](https://github.com/Donkie/Spoolman/assets/18683778/ec09a072-b91f-45f8-a2f1-7cb0b8090d7a)

![image](https://github.com/Donkie/Spoolman/assets/18683778/1673e2da-30ba-4efb-9894-e280d79ed90c)

**Desktop (please complete the following information):**
 - OS: KDE Neon 5.27
 - Google Chrome 
 - Version 120.0.6099.224 (Official Build) (64-bit)

**Update:
my camera is **Chicony Electronics Co., Ltd CNF9055 Toshiba Webcam** on old toshiba tecra with resolution 640x480

**Comment by Donkie** [comment]
Looks like by default the camera needs to be at least 640x640 resolution. I don't see why we need a resolution requirement on this though, so I will remove that.

Though I don't think you will get very good experience with such a low quality stream.

**Comment by ramaxa9** [comment]
not sure i will use it... just a bug report
btw, popup to allow camera access never happens
