### ISSUE TITLE
Debian install script can't find `requirements.txt`

### ISSUE THREAD

**Issue by CrazyIvan359** [Donkie/Spoolman#288]
**Describe the bug**
The Debian install script `scripts/install_debian.sh` is looking for `requirements.txt` in the project root but that file seems to ~have been moved to `tests_integration/`~ be missing from the repo. ~Not sure if it was intended to be moved or copied there, but if that's its new home then the script needs updating. I can submit a PR to correct this issue either way if you let me know which location is intended.~

**To Reproduce**
1. Run `scripts/install_debian.sh`

**Expected behavior**
The installer finds the requirements and installs them.

**Comment by Donkie** [comment]
There's currently somewhat of a mismatch with the install script and the releases. The script from master will not work until I have pushed the next release.

If you download the release zip like the README instructions say though, you will get the correct script version that does not look for requirements.txt

**Comment by CrazyIvan359** [comment]
Yeah that's what I get for doing this on a Sunday afternoon, forgot to switch to v0.15.0 🙃
