### ISSUE TITLE
Debian install script does not ensure `uvicorn` is installed

### ISSUE THREAD

**Issue by CrazyIvan359** [Donkie/Spoolman#289]
**Describe the bug**
The `uvicorn` package is not included in the list of packages to install, but is required and is not guaranteed to be installed on the host.

https://github.com/Donkie/Spoolman/blob/9d3fb022315136abfaa557aa8a6b993d36604596/scripts/install_debian.sh#L117

**To Reproduce**
1. Install standalone using `scripts/install_debian.sh`
2. Run Spoolman

I will submit a PR later today to add it to the list.

**Comment by CrazyIvan359** [comment]
This issue applies to the `master` branch not a release. Looking through some commits it seems that a migration from `pdm` to `uvicorn` is in progress at the moment, if that is incomplete then this may already be a known issue.

**Comment by Donkie** [comment]
It's added as a dependency here: https://github.com/Donkie/Spoolman/blob/master/pyproject.toml#L9
There is nothing wrong with the current setup.

**Comment by CrazyIvan359** [comment]
Those aren't being installed though, seems this is tied to #288 as well.

https://github.com/Donkie/Spoolman/blob/9d3fb022315136abfaa557aa8a6b993d36604596/scripts/install_debian.sh#L153

That line is looking for a requirements file, but seems that to install the listed dependencies from `pyproject.toml` you need to run `pip install .`.
