### ISSUE TITLE
Sorting Spools by Remaining weight returns error

### ISSUE THREAD

**Issue by cuiviemen** [Donkie/Spoolman#296]
**Describe the bug**
Sorting the spools by _Remaining weight_ returns HTTP/1.1 500 Internal Server Error

**To Reproduce**
1. Go to _Spools_
2. Click on _Remaining weight column header_
3. HTTP response status code 500 is returned and list of spools is empty (obviously)

**Expected behavior**
The spool list should be populated and sorted by Remaining weight accordingly.

**Screenshots**
![image](https://github.com/Donkie/Spoolman/assets/4427587/151a70f0-5a5d-49e4-bc73-a4c214df22cd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Edge, Chrome
 - Version 121.0.1, 121.0.2277.98, 121.0.6167.140

**Additional context**
Spoolman Version 0.16.0 is running as docker image, upgrade was performed with existing data from 0.15.0. Any other sortings are working properly.
Attached HAR file with captured HTTP request 
[SpoolmanIssue_Archive.24-02-02.09-50-43.har.json](https://github.com/Donkie/Spoolman/files/14138889/SpoolmanIssue_Archive.24-02-02.09-50-43.har.json)

**Comment by cuiviemen** [comment]
Remaining length produces the same error.

**Comment by Donkie** [comment]
Thanks for the report, this will be fixed in next release :)

**Comment by Donkie** [comment]
I have pushed an update now, see if it fixes it.

**Comment by cuiviemen** [comment]
I can confirm the 0.16.1 fixes the issue. Both Remaining weight and Remaining length sorting works.
