### ISSUE TITLE
Super excited about this, please continue working on this project!

### ISSUE THREAD

**Issue by Digityle** [Donkie/Spoolman#3]
Hello, I have a hx711 strain gauge (weight scale) and RFID tagging set up through home assistant (esp32), but I've been searching for a way to integrate it into klipper/mainsail. I liked the filament manager plugin that is available on Octoprint, but I really prefer the layout and simplicity of mainsail, just need a way to either pull info from home assistant or push it to moonraker, and display it in mainsail. I'm willing to contribute with testing, ideas, even throw a little cash your way if it means this project gets completed :) Again thank you!

**Comment by Donkie** [comment]
Hey!

That seems like a nice setup. I'm also excited about this. What you have is a perfect usecase for a service like this.

I'm still waiting for feedback from Arksine on this approach though, whether this is something he envisions moonraker supporting. I don't want to spend any more time on this if it will not be used.

**Comment by Digityle** [comment]
Have you browsed thru past comments on [This conversation?](https://github.com/Arksine/moonraker/pull/123#issuecomment-808113520)  May have some of the info you're looking for if you haven't seen it.

**Comment by Donkie** [comment]
Started my own attempt here https://github.com/Arksine/moonraker/pull/651

**Comment by Donkie** [comment]
Out of curiosity, could you explain a bit more how your strain gauge system works, and how you envision it integrating with Spoolman?

**Comment by Digityle** [comment]
Well, it's currently all run through home assistant and esphome. RFID reader (rc522) picks up a tag and sends it to home assistant. Automations in hass set input helpers for color, brand and spool weight (empty). Then the esp32 subtracts the empty spool weight and reports the difference to the frontend. Ideally it would be able to integrate with a spool manager such as yours to help calibrate more effectively (reported weight difference compared to slicer expected usage) but atm id be happy to just be able to see the values in the front end of mainsail, I'm currently running klipper inside an iframe in home assistant so I can keep an eye on it.

**Comment by Digityle** [comment]
Would also be nice for it to be able to pop a warning if not enough filament left on the roll for print

**Comment by solo2424** [comment]
I think barcode/qrcode would be great! Also a way to duplicate spools and make correct changes would be very useful.

**Comment by Donkie** [comment]
Closing this task since it's a mixed bag of feature requests. Please create any new issues if there isn't already an existing one for your ideas :)
