### ISSUE TITLE
Updating to 0.16 not work

### ISSUE THREAD

**Issue by PGlyre** [Donkie/Spoolman#300]
Describe the bug
I have followed your instruction to update to 0.16 from 0.15 but get an error 
" jq: error (at <stdin>:1): Cannot iterate over null (null)"

sudo systemctl stop Spoolman
sudo systemctl disable Spoolman
systemctl --user stop Spoolman
systemctl --user disable Spoolman

   No Problems

mv Spoolman Spoolman_old && \
mkdir -p ./Spoolman && \
source_url=$(curl -s https://api.github.com/repos/Donkie/Spoolman/releases/latest | jq -r '.assets[] | select(.name == "spoolman.zip").browser_download_url') && \
curl -sSL $source_url -o temp.zip && unzip temp.zip -d ./Spoolman && rm temp.zip && \
cp Spoolman_old/.env Spoolman/.env && \
cd ./Spoolman && \
bash ./scripts/install_debian.sh && \
rm -rf ../Spoolman_old

   Now i got This error "jq: error (at <stdin>:1): Cannot iterate over null (null)"

**Screenshots**
![image](https://github.com/Donkie/Spoolman/assets/25323238/c3ddfede-07b8-4130-b33d-0c6d21c7858b)

**Raspberry Pi 3B+**
 - OS: PiOS 2023-12-05

**Comment by Donkie** [comment]
Strange, looks like the download link didn't have any assets. Did you lose internet connection perhaps? Either way, I just pushed an update, try again please.

**Comment by PGlyre** [comment]
YES, now it's work..... THANK's
