### ISSUE TITLE
missing SQL columns (0.14>0.16)

### ISSUE THREAD

**Issue by veehexx** [Donkie/Spoolman#302]
i've just updated my docker stack with the latest version from 0.14 to 0.16 and i now appear to be missing the new required sql columns (like `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: remaining_weight`)

[spoolman log.log](https://github.com/Donkie/Spoolman/files/14156100/spoolman.log.log)

/home/app/.local/share/spoolman is correctly mounted and the spoolman webUI is loading my filaments on **some** pages but not working correctly at all.
I'm using your default docker config example (SQLite db)

i couldnt see any specific notes on the upgrade path and it looks like spoolman should be handling this itself at startup. seems not working for me.

**Comment by Donkie** [comment]
This has been fixed already and will be out in the next release, I will try push that today.

**Comment by Donkie** [comment]
I have pushed an update now, see if it fixes it.

**Comment by veehexx** [comment]
working well - thanks for the quick fix!
