### ISSUE TITLE
Add vendor defaults, for example empty spool weight

### ISSUE THREAD

**Issue by sprior** [Donkie/Spoolman#307]
**Is your feature request related to a problem? Please describe.**
Currently every time you enter a new filament you have to fill in fields like empty spool weight with no default value

**Describe the solution you'd like**
Vendors appear to change empty spool vendors rarely (though it does happen).  If you added a field to the Vendor record "current empty spool weight" and use that as a default in the create filament screen once the vendor has been selected you would save data entry time.  When the vendor changes their spools a user would change that in the vendor screen and from that time on new filaments would default to the new value.

**Describe alternatives you've considered**
You could start to capture all the spool possibilities for a vendor, but that's probably overkill for 90% of cases.

**Comment by Donkie** [comment]
Doesn't vendors have different spools for their different in-house brands? I think having this be default per vendor is too specific and would rarely be correct.
It's better to focus on having a filament database with known spool values instead.

**Comment by sprior** [comment]
Every spool I ever bought from Hatchbox no matter what the color or type of plastic) was the same, Esun as well.  When I say vendor I'm talking about the in-house brand so even if it did vary by brand it would still make sense to me to have a default spool weight associated with that brand.

**Comment by BigTrikerTom** [comment]
You could also define the empty coils as an independent area.
This would also allow you to store different coils for each manufacturer. Some manufacturers offer plastic, cardboard, refill and/or wooden spools. In addition, you wouldn't have to search the Internet or your own tables every time for the empty weight of the respective spool.

Just my 2 cents...

**Comment by spyder007** [comment]
Right now there is an empty spool weight at the filament level, which gives you the ability to set those weights per filament.  This should allow you to account for individual differences.

If there was an 'empty spool weight' at the vendor level that "fell through" to the filament, that would be ideal.  It's essentially a "default" value for empty spool weight that is applied when you create a new filament.

I would contend, though, that the Filament shouldn't have ANY spool values on it:  that's what Spool is for.  I've created a discussion (#338) to see if this would be a desirable change, or if I am just crazy.

**Comment by runtpacket** [comment]
> Doesn't vendors have different spools for their different in-house brands? I think having this be default per vendor is too specific and would rarely be correct. It's better to focus on having a filament database with known spool values instead.

I have been thinking about this lately. Could we setup a way to pull the filaments from a community ran db? Make it optional so you can either use local db or community driven one.

**Comment by Donkie** [comment]
Already in progress :) https://github.com/Donkie/SpoolmanDB
Will be available in next release

**Comment by spyder007** [comment]
This issue can probably be closed, considering #339 was release in 0.17 and the community DB support is in 0.18
