### ISSUE TITLE
Configurable currency for price

### ISSUE THREAD

**Issue by Donkie** [Donkie/Spoolman#31]
Somehow people should be able to make prices take a specific currency. Not sure where that would be configured though. Environment variable?

**Comment by zellneralex** [comment]
That is not as easy as it sounds. I would simple add a field where the User can add a current sign. Otherwise you will get complains that (put currency here) is missing.

more important you need the price per spool and not per filament. As an example I use a lot of eSun black abs+ and the spool varies between 18-21 EUR so currently there is no way to set the price of the active spools

**Comment by Donkie** [comment]
You'd input your currency with the currency code like EUR. There are libraries which support most if not all currencies out there. It's not just as easy as having a field where people can slap on the currency sign, since different currencies have different ways of formatting the money. Some have the currency sign before the value, some have after, for example.

My idea for it being on the filament level is that it would just be the "general" price of it, so you have a general understanding how much a print would cost for example, not for it to be an exact science. It could be a bit annoying having to input it for every spool.

But I guess I could keep the price on the filament, and just add a price on the spool as well, and if the spool price isn't set, the filament price would be used instead.

**Comment by zellneralex** [comment]
You can ask mete I am all in for units. My point is that you will find regions that buy it in more than on currency. 
we in Europe are mostly lucky that you can buy it mostly in EUR but consider other regions where the buy it from different countries in different currencies.

But I guess I could keep the price on the filament, and just add a price on the spool as well, and if the spool price isn't set, the filament price would be used instead. 
AZ: that is a good compromise.

I think about the UI here, where we could show the filament price in the history tab as long we know the weight, used spool and price per spool.
Weight is already there so we might need to add used spool ID to the moonraker meta data. Price could be queried at run time.

**Comment by Donkie** [comment]
I think then if you're buying with multiple currencies, and you want to track the costs using Spoolman, you would have to do a currency conversion to one standard currency manually. If we start to accept multiple different currencies in the same Spoolman instance, it would be very hard to do any cost calculations. Thirdparty apps that want to integrate with Spoolman also would need to handle these type of conversions.

I think the benefits outweigh the drawbacks forcing people to use a single currency

**Comment by fweber3** [comment]
Just looking over the fence a bit: PrusaSlicer takes "single currency" even further. Their hardcoded monetary unit is literally "money" or "money / kg".

What is the actual _usecase_ for the price data? Should that usecase _best_ be implemented in Spoolmanager, or somewhere else? (e.g. a business spreadsheet). These 2 questions should probably provide half the answer.

Apart from that: if it comes to that point, it would probably be nice to let old/new spools have differing prices. Inflation happens, old spools do too. (perhaps that is even already implemented, I do my cost tracking differently anyway).

**Comment by Donkie** [comment]
This has now been added
