### ISSUE TITLE
Moonraker is not permitted to restart service 'Spoolman'

### ISSUE THREAD

**Issue by thijstriemstra** [Donkie/Spoolman#310]
I upgraded from 0.15 to 0.16.1 ("manually"), added the moonraker update config and all looks good, except that I noticed this in the klipperscreen log:

```
Feb 10 00:02:59 klipperscreen KlipperScreen-start.sh[1204]:  Moonraker is not permitted to restart service 'Spoolman'.  To enable management of this service add Spoolman to the bottom of the file /home/foo/printer_data/moonraker.asvc.  To disable management for this service set 'is_system_service:
Feb 10 00:02:59 klipperscreen KlipperScreen-start.sh[1204]:  False' in the configuration for this section.
```

Seems this is a bug?

fluidd 1.28:

![afbeelding](https://github.com/Donkie/Spoolman/assets/305679/8ff24a26-3959-4c5c-843f-fc9f42da8109)

moonraker config:

```ini
[update_manager Spoolman]
type: zip
channel: stable
repo: Donkie/Spoolman
path: ~/Spoolman
virtualenv: .venv
requirements: requirements.txt
persistent_files:
  .venv
  .env
managed_services: Spoolman
```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox

**Comment by Donkie** [comment]
Have you tried doing as it says? This is a Moonraker issue, not Spoolman

**Comment by Loogl3** [comment]
exactly as noted, go to printer_data and edit the file, adding "Spoolman" to the bottom
~ $ cd printer_data
nano moonraker.asvc

![image](https://github.com/Donkie/Spoolman/assets/117388662/dd5f3c7b-ec99-443a-84f5-abb6eae6f386)
