### ISSUE TITLE
Request to add a custom identifier

### ISSUE THREAD

**Issue by 0gl0** [Donkie/Spoolman#321]
Request to add a custom identifier
Request for custom sorting
![屏幕截图 2024-02-29 110547](https://github.com/Donkie/Spoolman/assets/87184793/8dd728a7-8710-4d72-ae48-aebd0e2e3642)

**Comment by Donkie** [comment]
The way the ID is setup is central to how the whole backend and frontend works. Having custom IDs would require huge changes for little gain, which is not something worth investing time in. I suggest utilizing the "comment" field instead, there you can write whatever you want and still have it sortable.
