### ISSUE TITLE
Can't add new location

### ISSUE THREAD

**Issue by bofh69** [Donkie/Spoolman#322]
**Describe the bug**
I can't add a new location when creating a new spool or editing an old spool.

**To Reproduce**
I go to spools, click create, press the location field, then I get a "No data" box showing, but the field is not active/I can't write anything in it.

**Expected behavior**
I expected to be able to write the name of the location.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04LTS
 - Browser: Firefox
 - Version: 121

**Additional context**
This is a new install with the latest docker image.

**Comment by Donkie** [comment]
Just below where it says No Data you should have a text input where you can type in a new location. I just tried it in firefox and it works fine for me.
![image](https://github.com/Donkie/Spoolman/assets/2332094/6a297dca-f6fa-41f9-9c7e-e15881e7ee9d)
Do you see this field?

**Comment by bofh69** [comment]
Yes, I missed that one. Sorry about that. It was easier to see once another location had been added.
