### ISSUE TITLE
Error: No module named 'components.spoolman' in Moonraker

### ISSUE THREAD

**Issue by ODog2028** [Donkie/Spoolman#331]
After I installed Spoolman, I added the entry below into the moonraker.conf file.
```
[spoolman]
server: http://localhost:7912
sync_rate: 5
```
 After I did that and rebooted moonraker, I got a warning in Fluidd that said:
```
Unparsed config section [spoolman] detected. This may be the result of a component that failed to load. In the future this will result in a startup error.
```
The moonraker log said:
```
[moonraker.py:load_component()] - Unable to load component: (spoolman)
Traceback (most recent call last):
  File "/home/mks/moonraker/moonraker/moonraker.py", line 233, in load_component
    module = importlib.import_module("components." + component_name)
  File "/home/mks/moonraker-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'components.spoolman'
```
The [full log file](https://github.com/Donkie/Spoolman/files/14620818/moonraker.log) is attached. My printer is a Elegoo Neptune 4 Pro with native Klipper/Moonraker/Fluidd. If I need to add other information, please to me.

**Comment by Donkie** [comment]
This is a Moonraker issue so the Spoolman github is not the right place to report it. Anyway, your moonraker installation is too old which causes this issue. You need to update it. Moonraker added support for Spoolman around summer last year.

**Comment by ODog2028** [comment]
I was able to fix it by updating Moonraker (after a lot of work). Thanks for bringing that to my attention.
