### ISSUE TITLE
Missing requirements.txt leads to failing install

### ISSUE THREAD

**Issue by dw-0** [Donkie/Spoolman#332]
**Describe the bug**
When executing install_debian.sh, the script will fail here:
https://github.com/Donkie/Spoolman/blob/v0.16.1/scripts/install_debian.sh#L153
As it will not find the expected requirements.txt
```sh
pi@minion:~/Spoolman $ bash ./scripts/install_debian.sh
Python 3.9 or later is installed (Current version: 3.9.2)
Updating apt-get cache...
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Updating pip...
Pip updated successfully.
Installing system-wide pip packages needed for Spoolman...
Installing Spoolman backend and its dependencies...
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**To Reproduce**
1. Execute install_debian.sh script.
2. Wait :)

**Expected behavior**
A requirements.txt file present, if it holds necessary dependencies

**Comment by rufinus** [comment]
requirements are generated during packaging the release. see the release files zip and take the file from there. 

see https://github.com/Donkie/Spoolman/blob/a68e0d59bd18983403cc56497bdc9bca84285886/.github/workflows/ci.yml#L60

**Comment by Donkie** [comment]
As @rufinus said, you need to download the .zip from the release page: 
https://github.com/Donkie/Spoolman/releases/tag/v0.16.1

spoolman.zip here:
![image](https://github.com/Donkie/Spoolman/assets/2332094/c814c8cd-d299-4fa2-884e-e548c9016435)

**Comment by dw-0** [comment]
I see, my bad. Sorry. I did a git pull (was on v0.13.x), checked out the recent tag and thought it should work when i run the script ^^ i was taught better. Thanks.
