### ISSUE TITLE
Hardware?

### ISSUE THREAD

**Issue by NonaSuomy** [Donkie/Spoolman#34]
What hardware do you use to actively measure the spool weights in mainsailOS while the printer is printing to update spoolman is there a page about this?

Forgive me if it is covered someplace.

Maybe you can enable discussion on the Repo as well so stuff like this doesn't need to go in the issues tracker.

**Comment by Donkie** [comment]
I don't think anyone has implemented any weight measurement system to update Spoolman yet.

The way it works by standard is by reading the extruder G codes and converting that to grams of consumed filament using the density and diameter of the filament. The consumption is then sent to Spoolman, which tracks the total usage.

**Comment by NonaSuomy** [comment]
Ok that is interesting, thank you, will have a look at that. This is all you need to get it running?

# moonraker.conf

[spoolman]
server: http://192.168.0.123:7912
#   URL to the Spoolman instance. This parameter must be provided.
sync_rate: 5
#   The interval, in seconds, between sync requests with the
#   Spoolman server.  The default is 5.

# printer.cfg

[gcode_macro SET_ACTIVE_SPOOL]
gcode:
  {% if params.ID %}
    {% set id = params.ID|int %}
    {action_call_remote_method(
       "spoolman_set_active_spool",
       spool_id=id
    )}
  {% else %}
    {action_respond_info("Parameter 'ID' is required")}
  {% endif %}

[gcode_macro CLEAR_ACTIVE_SPOOL]
gcode:
  {action_call_remote_method(
    "spoolman_set_active_spool",
    spool_id=None
  )}
  
  It will then start tracking the spool usage nothing more to do?

**Comment by Donkie** [comment]
Yup that should be about it, and then running your set active spool GCode of course.
