### ISSUE TITLE
Prusa Slicer Set Active Spool Filament Gcode

### ISSUE THREAD

**Issue by TMTYD** [Donkie/Spoolman#342]
**Describe the bug**
If I put the code: SET_ACTIVE_SPOOL ID= in the custom filament gcode and specify the ID of the spool, then the spool in mainsail is not automatically activated

**Expected behavior**
Actually, I expect that as soon as the gcode file is uploaded, it will automatically activate the spool with which I want to print

**Screenshots**
![grafik](https://github.com/Donkie/Spoolman/assets/29516076/e0fc885f-4a2a-4498-9803-2d9b0317a2d7)
![grafik](https://github.com/Donkie/Spoolman/assets/29516076/01e92143-c223-4d3e-9d26-474948cdab62)
![grafik](https://github.com/Donkie/Spoolman/assets/29516076/5866e1ca-c2a4-43a1-a34e-7793b7c11413)
![grafik](https://github.com/Donkie/Spoolman/assets/29516076/cfae6dec-4d00-47e9-b832-84b36743c5db)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 124.0.1

**Additional context**
What is the correct filament Gcode to automatically activate the spool?

**Comment by TMTYD** [comment]
Ok if I understand correctly, is the code in the filament Gcode correct and when I start printing then the spool is automatically selected?

**Comment by rufinus** [comment]
> Ok if I understand correctly, is the code in the filament Gcode correct and when I start printing then the spool is automatically selected?

correct.

**Comment by TMTYD** [comment]
ok thx

**Comment by TMTYD** [comment]
it works thx

**Comment by yourbuddydinec** [comment]
As a secondary thing I'm not sure the exact code for prusaslicer so may have to modify some but this works perfectly in orcaslicer. For the filament's start gcode add the `SET_ACTIVE_SPOOL` code
![image](https://github.com/Donkie/Spoolman/assets/52755257/a3d39f43-7243-4651-a5d8-5aad83ef9d70)
Then in the print start gcode you can add `{filament_start_gcode[0]}` to execute the filament start gcode at the start of your machine start gcode and it will select it as soon as the print starts and not have to wait for it to get to that in your start macro.
![image](https://github.com/Donkie/Spoolman/assets/52755257/51623829-90d8-400c-b49a-a9769b1ba9ca)
Doing this also allows you do keep letting it set your gcode based on the filament selected in the slicer.
