### ISSUE TITLE
The ability to `Save As` if I want to save something from `Print QR Code` instead of using print dialog. IE a jpg, png, etc

### ISSUE THREAD

**Issue by MahindraPersaud** [Donkie/Spoolman#348]
**Is your feature request related to a problem? Please describe.**
One of the issues I've faced is I have a small thermal printer that I can use to print labels. This printer is a 40x15mm (lxw) and allows me to be able to easily print things on it such as images. However, there's currently no easy to get the QR codes generated from `Print QR Codes` to a jpg etc. I first have to click `Print` -> `Save as PDF` -> Convert PDF to Jpg. 

**Describe the solution you'd like**
I would like a button next to the `print button` that would allow me to instead `save as` using the file system dialog to be able to save the QR code as a jpg,png, etc

**Describe alternatives you've considered**
The alternative that I've had to complete is first have to click `Print` -> `Save as PDF` -> Convert PDF to Jpg. 

**Additional context**
No other additional Context at the moment. Please feel free to ask any questions and I'll be more than happy to help. I'm currently trying to implement this myself in a fork, however, I have no knowledge of react.

I was thinking of utilizing https://www.npmjs.com/package/native-file-system-adapter as a way to ensure that we could get the system dialog for varying browsers as `window.showSaveFilePicker()` is only for chrome + MS Edge browsers.

**Comment by ressu** [comment]
I was actually thinking about this feature request too. Using P-Touch on linux needs jpg files too. So this would be a very useful feature.
