### ISSUE TITLE
Add a weight field to spool, to overwrite filament spool weight

### ISSUE THREAD

**Issue by atl285** [Donkie/Spoolman#357]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I have a bunch of spools which are respooled with other filament. So they are not the original spools which the filament normally uses. So I would prefer to have the **weight** field as part of the spool table. On creating a spool, the weight field should be filled with the filament based spool weight value (think this as a default) and can changed individually.

**Comment by spyder007** [comment]
This is already handled by #339, which should be out in the next release.

**Comment by spyder007** [comment]
#339 has been closed, this can probably be closed.
