### ISSUE TITLE
Double Space in text (in weblate)

### ISSUE THREAD

**Issue by ThaPg** [Donkie/Spoolman#358]
**Describe the bug**

In following keywords and texts:
a) Keyword: spool.fields_help.initial_weight
    Text: The initial Weight of the filament (net weight).  This value may come from the filament, but is tracked at the spool level to allow for individual variations the weight of filament on the spool.

b) Keyword: spool.fields_help.spool_weight
    Text: The weight of the spool when it is empty.  This value may come from either the filament or the vendor, but is tracked at the spool level to allow for individual variations of the weight of an empty spool.

After the first sentense, in both texts, exists double space. 

**To Reproduce**
Weblate translation window from english to greek (and possible in all languages, due to problem in english language). In screenshots are the double dots in red square from weblate webpage.

**Expected behavior**
Rewrite the two sentences with one space.

**Screenshots**
English:
![image](https://github.com/Donkie/Spoolman/assets/97054764/8405a182-a986-453e-93b0-9f6cba2484d1)
![image](https://github.com/Donkie/Spoolman/assets/97054764/77e7b61e-5c78-4089-9554-59ea0e6f2751)
![image](https://github.com/Donkie/Spoolman/assets/97054764/b8c9369d-df9a-4343-af69-c007ccfed061)

Greek:
![image](https://github.com/Donkie/Spoolman/assets/97054764/678d4a0e-6b6a-4d08-9d69-bf468109165a)

**Comment by Donkie** [comment]
You can change the english text in Weblate as well

**Comment by ThaPg** [comment]
I didn't know that, I thought it was something like a bug. Thanks for the info. 

I think the issue is closed?
