### ISSUE TITLE
Metrics endpoint is not working, showing the main page

### ISSUE THREAD

**Issue by hakan42** [Donkie/Spoolman#363]
**Describe the bug**
Having set SPOOLMAN_METRICS_ENABLED to TRUE, the metrics endpoint is still not available

**To Reproduce**
1. Start docker container with --env SPOOLMAN_METRICS_ENABLED=TRUE
2. Run "curl http://my-server:7912/metrics"
4. Observe that the main page of the application is being shown: "<noscript>You need to enable JavaScript to run this app.</noscript>"

**Expected behavior**
A parseable metrics output should be shown

**Linux Server**
 - OS: Ubuntu 22.04, running Docker version 24.0.5,
 - Spoolman version: "Starting Spoolman v0.16.1 (commit: babb95d) (built: 2024-02-04 10:12:19+00:00)" (dockerized)
 - Browser N/A
 - Version N/A

**Running the container as:**

    docker run \
       --rm \
       --name ${DOCKER_NAME} \
       --hostname ${DOCKER_NAME} \
       --publish 7912:8000 \
       --env PUID=$(id -u) \
       --env PGID=$(id -g) \
       --env TZ=Europe/Berlin \
       --env SPOOLMAN_LOGGING_LEVEL=DEBUG \
       --env SPOOLMAN_METRICS_ENABLED=TRUE \
       --mount source=${DOCKER_NAME}_data,target=/home/app/.local/share/spoolman \
       ${DOCKER_IMAGE}

**Comment by Donkie** [comment]
0.17 was now pushed which should include the prometheus support, see if it works better now.

**Comment by hakan42** [comment]
Thank you, with that build, it does indeed work.
