### ISSUE TITLE
docker-compose.yml: `version` is obsolete 

### ISSUE THREAD

**Issue by platini76** [Donkie/Spoolman#366]
hello thanks for .17 version!
how to solve this?

root@spoolman:~# docker compose pull && docker compose up -d
WARN[0000] /root/docker-compose.yml: `version` is obsolete 
[+] Pulling 1/1
 ✔ spoolman Pulled

**Comment by Donkie** [comment]
That is just a warning, don't worry about it. You can remove the  first version line in the docker compose if it annoys you.

**Comment by platini76** [comment]
thanks!
