### ISSUE TITLE
Can't clone Filament or Spool

### ISSUE THREAD

**Issue by THUWE-DEV** [Donkie/Spoolman#369]
If i try to clone a Filament or Spool with the contextmenu i get an white screen.

**To Reproduce**
1. Call the Filament or Spool clone via contextmenu
2. Now the Page turn to white

**Screenshots**
Browser Error log:
![image](https://github.com/Donkie/Spoolman/assets/54943562/ec68e263-90e0-41bf-b643-ad2d79be1070)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser Edge 124.0.2478.67
 - Slicer: Orca 2.0.0 / Fluidd 1.30.0

**Comment by Donkie** [comment]
Please update to 0.17 and see if it works

**Comment by THUWE-DEV** [comment]
Thanks for your quick response. After updating spoolman to 0.17, problem is solved 👍
