### ISSUE TITLE
Return estimated remaining_length in addtion to remaining_weight

### ISSUE THREAD

**Issue by akonkol** [Donkie/Spoolman#37]
I am looking  to grab the filament required for a print and see if that amount is available on the active spool. If there is not enough filament on the spool to satisfy the print I want to throw an error in the UI or return something like a `409` (which may be more complex).

The amount filament required for a gcode file can be found via a call to [` /server/files/metadata?filename={filename}`](https://moonraker.readthedocs.io/en/latest/web_api/#get-gcode-metadata). The value provided by the slicer is provided in [`millimeters`](https://github.com/Arksine/moonraker/blob/a7e154fbe4e1f3dec4fc051e24af2d6188d979bd/docs/api_changes.md?plain=1#L304)

Although you could leave it up to the developer to create a helper function as you done [here](https://github.com/Donkie/Spoolman/blob/0cdb496a1de83c5a1547288e141dcb4b5e88deac/spoolman/math.py#L6) I think it would be nice if `Get Spool` returned `remaining_length` as well as `remaining_weight`

**Comment by Donkie** [comment]
Good idea, this is an easy addition
