### ISSUE TITLE
Bug: Sorting by remaining weight is not correctly sorted

### ISSUE THREAD

**Issue by Ash3781** [Donkie/Spoolman#375]
**Describe the bug**
Sorting by remaining weight is not sorted correctly

**To Reproduce**
1. Sort Spools (in any direction) by remaining weight

**Expected behavior**
I'd expect it to show me my Spools in a correctly sorted manner, if I click on sorted by remaining weight

**Screenshots**
![image](https://github.com/Donkie/Spoolman/assets/37660156/fa000367-4f3a-4f9d-b3b5-83faf8a7e37a)

**Spoolman Host (please complete the following information):**
 - Installation type: Standalone
 - Installed version: 0.17.0 (4f93fdd)
 - OS and Distro: Debian 12
 - Database type: Whatever the default is, I don't remember, sorry

**Desktop (please complete the following information):**
 - OS: NixOS (Tho I don't get how that is relevant for an web page)
 - Browser: Firefox

**Comment by wollew** [comment]
I can confirm this. My guess is that this happens when you have spools/filaments in your DB that do not have a spool weight set, but I didn't really try to track this down.

**Comment by Donkie** [comment]
Should be fixed in next release, 0.18.
Please reopen this issue if it still appears then.
