### ISSUE TITLE
Text missing (edit: probably just translations missing - due to new system used?)

### ISSUE THREAD

**Issue by drlauridsen** [Donkie/Spoolman#376]
In version 0.17 there are a couple of places where the text is missing in a lot of language, including English and Danish.

Eg in the add/edit filament page
![Screenshot 2024-05-13 at 19-55-56 Create Spool Spoolman](https://github.com/Donkie/Spoolman/assets/61352332/4794cb6b-523f-4003-95d1-b9dacd7463be)

And also in the vendors page

**Comment by Donkie** [comment]
Strange, I don't see this in the 0.17.0 I have deployed. Did you install using Docker or standalone? Can you show what build you have at the bottom of the page?

**Comment by drlauridsen** [comment]
It says 0.17.0, installed with docker

In English and Danish the variablename is shown, but in German it is shown
correctly.

man. 13. maj 2024 20.02 skrev Donkie ***@***.***>:

**Comment by Donkie** [comment]
Which tag did you pick for docker?
What is the build hash at the bottom? This number:
![image](https://github.com/Donkie/Spoolman/assets/2332094/cb4832e4-894c-4c77-8d60-2bb4c986f24d)

**Comment by drlauridsen** [comment]
Tag ghcr.io/donkie/spoolman:latest
Build hash






man. 13. maj 2024 20.27 skrev Donkie ***@***.***>:

**Comment by Donkie** [comment]
You didn't provide any hash

**Comment by Donkie** [comment]
We have exact same version.
I just realised, try refreshing and clearing your cache. Do that by doing Ctrl + F5 in spoolman

**Comment by drlauridsen** [comment]
Refresh did not change anything,  but clearing cache did..

Problem solved

man. 13. maj 2024 21.31 skrev Donkie ***@***.***>:
