### ISSUE TITLE
Wont install on my syste

### ISSUE THREAD

**Issue by partumre3d** [Donkie/Spoolman#388]
*after running initial install script 

I go to next step to update and when update script  for spoolman is run
I get errors stating spoolman.service does not exist and spoolman service was not loaded.

I'm expecting the update to co.plete and then see the install refected in my fluidd UI as shown in guide. 

![Screenshot_20240524_194037_RaspController](https://github.com/Donkie/Spoolman/assets/158579121/63ba0731-41a8-49d5-9675-f7a89a8d9fae)

![Screenshot_20240524_194934_RaspController](https://github.com/Donkie/Spoolman/assets/158579121/9b6d37ce-48cd-47f3-a5d2-4dd20950b701)

Qidi xmax3
Standalone
No sure where to find my spoolmanwebsite esp if it wont even install and that would just landing page within internal network unless it can be accessed remotely. No Install so can't answer.
Think it's raspian I've also seen debian and armbian mentioned.
Think I have sql but I'm a novice so can't answer that honestly or confidently.

Laptop is Windows  mobileraker app on phone is android versions 
I use Microsoft edge browser.

**Spoolman Host (please complete the following information):**
 - Installation type: [Docker or Standalone]
 - Installed version: [e.g. 0.17.0, can be found at the bottom of your spoolman website if you don't know]
 - OS and Distro: [e.g. Ubuntu, Raspbian]
 - Database type: [SQLite, PostgreSQL, etc]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android, ...]
 - Browser [e.g. Chrome, Firefox, Safari, ...]

**Additional context**
No idea how to use docker. Also I have run same script in different terminal command apps to ssh and no luck.

**Comment by Donkie** [comment]
The errors you show here are due to you already having attempted to install Spoolman but it probably failed as you have said. Go to your home directory (`cd ~`) and remove all folders related to Spoolman (e.g. `rm -R Spoolman`).

After you're sure Spoolman is gone, try following the instructions in README again for a standalone install. If any errors appear, note them down/take a screenshot and show me here before you try anything else.

**Comment by partumre3d** [comment]
Ok thank you I will try that now. And get back to you with what you
suggested if I have any issues.

Kindest regards
Lawrence
