### ISSUE TITLE
Expose label print API

### ISSUE THREAD

**Issue by jimbolimbo3** [Donkie/Spoolman#391]
I'd like to get the QR code and the descriptions using an API, Since it can be useful for external printing solution, like
[https://github.com/NaitLee/Cat-Printer](https://github.com/NaitLee/Cat-Printer) , and other OPOS/POS printer solution.

**Comment by Donkie** [comment]
Spoolmans API is already completely open. This is the same API that the web client uses. You can access the documentation at your local installation: `http://spoolmanip:port/api/v1/redoc`

For example, to get info about a spool you can do a HTTP GET: `http://spoolmanip:port/api/v1/spool/<spool_id>`

The QR code is entirely generated on the client side in your browser in the web client, so no API can provide that for you at this point. But if you find some other utility to generate QR codes on the fly, the QR codes simply contain the spool ID formatted using this format: `web+spoolman:s-<spool_id>`

Hope this solves your needs :)
