### ISSUE TITLE
Print multiple copies of labels

### ISSUE THREAD

**Issue by KoiosLabs** [Donkie/Spoolman#398]
**Is your feature request related to a problem? Please describe.**
I often store my filament unopened, in its manufacturer's vacuum bag until its needed (i keep several in stock of common colours).  To make my life easier I print 2 labels, one to put on it, and one to keep with it for when i open it, so as not to get lazy and forget to label it.

**Describe the solution you'd like**
A number of copies field on the print dialog, to have it print 2x or 3x of each label as needed.

**Describe alternatives you've considered**
printing twice, but then the collation is a pain in the butt, if it was done in software, it can keep the labels together on the page, as it prints.

**Additional context**
I may work on a PR for this when i have some time, but didnt want to forget about the need, and if someone else has more time/motivation...

**Comment by Donkie** [comment]
Great suggestion, should be easy to implement :)
