### ISSUE TITLE
If i change a spool mid print can i also change filament being used to account for usage of both, while printer is paused

### ISSUE THREAD

**Issue by rishi4999** [Donkie/Spoolman#408]
**Describe the solution you'd like**
Whenever my printer pauses, i should be able to change the filament being used to account for multicolor prints

**Comment by Donkie** [comment]
Spoolman itself doesn't decide what filament is having its weight deducted as you print, that's up to Moonraker/Octoprint to handle. So technically Spoolman already supports what you're asking for, hence why I will close this issue.

I believe some people have managed to achieve multi-color filament switches using macros in Moonraker. Perhaps you can head over to Moonraker Github or Discord and ask for advice.

**Comment by sntlewis** [comment]
I have a call the Moonraker Spool macros for the filament change portion of the slicer.  Just got to make sure to get the right Spool Id.  As it is done here in the slicer, I don't have to worry about setting the spool everytime I switch spools.
