### ISSUE TITLE
Websocket subscription

### ISSUE THREAD

**Issue by Donkie** [Donkie/Spoolman#41]
Add support for subscribing to changes to spools/filaments/vendors via websockets, so you can receive updates immediately without having to poll.

**Comment by Disane87** [comment]
That would be benefitial indeed., Currently I'm writing an Home-Assistant integration for Spoolman and this would become pretty handy

**Comment by Donkie** [comment]
The Get spool API actually already now contains an experimental web socket endpoint. See the OpenAPI documentation: https://donkie.github.io/Spoolman/#tag/spool/operation/Get_spool_spool__spool_id__get

**Comment by Disane87** [comment]
Great! Will dig into this :)
