### ISSUE TITLE
Color for spool?

### ISSUE THREAD

**Issue by tome9111991** [Donkie/Spoolman#414]
Hi, currently, you have to create a new filament for each different color, even if it's from the same manufacturer and the same material. Wouldn't it make more sense to create a new spool with the filament and manufacturer and then choose the color there?

This way, if you have the same filament from the same manufacturer, you always have to create a new filament and change the color, while also creating a new spool at the same time.

**Comment by Donkie** [comment]
"Filament" is equivalent to a specific article of a manufacturer. A "spool" is an instance of an article. That's how  the entire system is designed.

You can easily create filaments of different colors but same parameters of the rest by clicking the Clone button in the list view after you have created the first filament :)
