### ISSUE TITLE
Pull color information from filamentcolors.xyz

### ISSUE THREAD

**Issue by Cellivar** [Donkie/Spoolman#421]
**Is your feature request related to a problem? Please describe.**

I learned about [the delightful website project](https://filamentcolors.xyz/library/) of a guy trying to standardize the color profile of printer filaments. His website <https://filamentcolors.xyz> has an impressive library of filaments already, and he's got quite the backlog yet to print. Their photo calibration setup is one of the most robust attempts at consistent results across different filaments, making it much more reliable when looking to compare filament colors between different manufacturers.

When adding filaments to my Spoolman instance I've been looking up the color information from the filamentcolors website manually. It would be very nice if this happened automatically.

**Describe the solution you'd like**

When adding a new filament or importing an external filament that matches one on filamentcolors.xyz, automatically add the color information to Spoolman from that source.

**Describe alternatives you've considered**

Continue the drudgery of copy/pasting between browser tabs.

**Additional context**

There's a public API for the website, with a polite request to chip in to help fund the website.

<https://github.com/itsthejoker/filamentcolors.xyz>

I would be willing to make a significant donation on behalf of Spoolman development if this feature were to be seriously considered.

**Comment by itsthejoker** [comment]
See also: https://github.com/Donkie/Spoolman/discussions/372

**Comment by Cellivar** [comment]
GitHub Search failing me apparently, didn't see the discussion. Sorry for the duplicate.
