### ISSUE TITLE
MainsailOS integration

### ISSUE THREAD

**Issue by bodak** [Donkie/Spoolman#43]
I am adding the steps here I took to add Spoolman to [MainsailOS](https://github.com/mainsail-crew/MainsailOS).
### (1) Install on MainsailOS
```
cd ~/
git clone https://github.com/Donkie/Spoolman.git
mv Spoolman spoolman
virtualenv -p python3 ~/spoolman-env
source ~/spoolman-env/bin/activate
cd spoolman
git checkout v0.9.1
pip install -U pip pdm
pdm sync --prod
```

### (2) Build npm assets on dev PC/Mac
(This assumes you have npm set up there)
```
git clone https://github.com/Donkie/Spoolman.git
cd Spoolman/client
npm install
echo "VITE_APIURL=/api/v1" > .env.production
npm run build
```
### (4) Create spoolman.service under /etc/systemd/system/
```
[Unit]
Description=Spoolman
Documentation=https://github.com/Donkie/Spoolman
After=network-online.target
Wants=network-online.target
Before=nginx.service

[Install]
Alias=spoolman
WantedBy=multi-user.target

[Service]
Type=simple
User=pi
RemainAfterExit=yes
WorkingDirectory=/home/pi/spoolman
Environment="PATH=/home/pi/spoolman-env/bin"
ExecStart=/home/pi/spoolman-env/bin/uvicorn spoolman.main:app --host 0.0.0.0 --port 8000
Restart=always
RestartSec=10
```

### (5) Add to moonraker.conf
```
[spoolman]
server: http://localhost:8000
sync_rate: 5
```

**Comment by Donkie** [comment]
This is great, goes in hand with #27 , thank you!

**Comment by bodak** [comment]
@Donkie I had to change the following code to avoid an error with my setup:
`sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
` caused by `registered=item.registered` in `/api/v1/models.py`.

in `spoolman/database/models.py` change `registered: Mapped[datetime] = mapped_column(default=func.now())` into `registered: Mapped[datetime] = mapped_column(default=datetime.utcnow())`

Your code did work as a Docker image, so this must be something with the standalone install.

**Comment by Donkie** [comment]
Interesting. But that code will not give you the correct default value. It will be what the time were when Spoolman was started, not what time the row was added to the database.

**Comment by bodak** [comment]
Thanks. I can probably patch that in the `create` methods if needed.

It would be good to understand why `func.now()` is called outside the session with `expire_on_commit=False`.

**Comment by RPhilbo** [comment]
Hi @bodak , thank you for this tutorial!

Unfortunately, following it in (1) , after "pdm sync --prod" i got the following error: 
"[ProjectError]: Lock file does not exist, nothing to install"

**Comment by bodak** [comment]
@RPhilbo
(1) The `[pdm.lock](https://github.com/Donkie/Spoolman/blob/master/pdm.lock)` file should be there in the root directory if you git cloned the repo. Check if you are in the right directory.
(1a) Probably worth to `git checkout v0.9.1`
(2) An alternative to `pdm sync --prod`: get the latest pip with `pip install -U pip` and just install using the `pyproject.toml` using `pip install -e .`. This is what I did first as I am not familiar with `pdm`.
(3) Try to first run it from the cli before setting up the service. `source ~/spoolman-env/bin/activate` & `uvicorn spoolman.main:app --host 0.0.0.0 --port 8000`
(4) Check the patches I mentioned above. You also need to change within every `async def create` method within the database folder and add `registered=datetime.utcnow(),` to get the correct datetime.

**Comment by RPhilbo** [comment]
@bodak 
you answered very fast, thank you. After my comment here i found #12 and that worked for me.

**Comment by bodak** [comment]
That is certainly an easier way for now.

Running through Docker adds some overhead and I am already concerned with my Raspbery PI 3A+'s stability when running MainsailOS, a single camera and now spoolman.

**Comment by platini76** [comment]
I have an error on first point:
[VirtualenvCreateError]: Can't resolve python interpreter

**Comment by BioCookieYT** [comment]
> 

Same here

**Comment by srbjessen** [comment]
I get this at "npm install"
PS C:\Users\Søren\Spoolman\client> npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'spoolman-ui@0.1.0',
npm WARN EBADENGINE   required: { node: '16.x' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.1.0' }
npm WARN EBADENGINE }

**Comment by CD1010** [comment]
Getting this error running this command: 
pdm sync --prod -v

Followed steps above.

 ✖ Install psycopg2-binary 2.9.6 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 286, in install_candidate
    self.manager.install(can)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/models/candidates.py", line 414, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/builders/base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.

For further information please check the 'doc/src/install.rst' file (also at
<https://www.psycopg.org/docs/install.html>).

Traceback (most recent call last):
  File "/home/pi/spoolman-env/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/cli/commands/sync.py", line 44, in handle
    actions.do_sync(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/cli/actions.py", line 238, in do_sync
    synchronizer.synchronize()
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 454, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet

**Comment by Donkie** [comment]
Please follow the official standalone install instructions in Spoolman's README instead

**Comment by CD1010** [comment]
I see now. My bad.  Got it installed using your readme.

**Comment by Donkie** [comment]
Closing this. It should either be opened as a discussion or opened as an issue in MainsailOS's github.
