### ISSUE TITLE
Picking a color for multi color filament adds more color fields without setting the color

### ISSUE THREAD

**Issue by jaypikay** [Donkie/Spoolman#433]
**Describe the bug**
Picking a color for multi color filament adds more color fields without setting the color.
Each color picker value change adds multiple new color fields.
The color of the select field is not updated correctly.

**To Reproduce**
1. Go to 'Filaments -> Edit Filament'
2. Click on 'Color: Multi -> Coextruded or Logitudinal' (same behavior
3. Open color picker and select any color. Color will always be red or black.
4. No need clicking the plus button.
5. See error.

**Expected behavior**
Change color to selected value.

**Screenshots**
Firefox:
![image](https://github.com/user-attachments/assets/d9d920fc-a479-41e9-b221-e4c1d5c8b43a)

Chromium:
![image](https://github.com/user-attachments/assets/75ba8b62-f6b8-4115-ab02-dc911f18154c)

**Spoolman Host (please complete the following information):**
 - Installation type: Docker
 - Installed version: 0.19.0
 - OS and Distro: Arch Linux
 - Database type: SQLite

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 128, Chromium 127

**Comment by mfraser** [comment]
Just upgraded to 19.0 and encountered this when trying to use multi colour filament.

**Comment by Donkie** [comment]
This should be solved in the latest release, please try it out, re-open or recreate the issue if there is still some problem. :)

**Comment by TimetravelerDD** [comment]
i confirm, it works now flawlessly.
