### ISSUE TITLE
Currency setting is not able to be changed

### ISSUE THREAD

**Issue by jeremyawarren15** [Donkie/Spoolman#436]
**Describe the bug**
When I go to the settings page in the general tab and attempt to change the currency I am not receiving any message that it failed to update. However, when I go to the developer tools and look at the request I can see that I am getting a 400 error `{"message":"Setting currency must be a string."}`.

**To Reproduce**
1. Go to the settings page in the general tab
2. Enter `USD` for currency
3. Click "Save"

**Expected behavior**
I expect that I should receive a message saying that my currency has been updated and that setting be saved.

**Spoolman Host (please complete the following information):**
 - Installation type: Standalone
 - Installed version: 0.19.0 
 - OS and Distro: Debian 12
 - Database type: SQLite

**Desktop (please complete the following information):**
 - OS: PopOS
 - Browser Chrome

**Comment by jeremyawarren15** [comment]
I also just installed v0.19.2 on Unraid to kind of narrow down if it was just my setup and I'm having the same issue.

**Comment by WorldsWorstAstronaut** [comment]
Same here. Fresh install of v0.19.0 on a raspberry pi running bullseye
