### ISSUE TITLE
[BUG] Incorrect Filament usage recorded

### ISSUE THREAD

**Issue by ataa** [Donkie/Spoolman#451]
Installed the SpoolMan for Klipper using Kiauh, added manufacturer, filament and the spool, for the first print everything was logged fine, but during the second print (17.1 Meters total usage) I noticed that the remaining filament is 0 and the listed total usage is 10,303,099.4 mm and Used Weight of 30,729.5 g!

Couldn't find anything related in the log file, all I can see in the log is "now listening on pool" and "has stopped listening on pool"

 - Installation type: Installed using KIAUH
 - Installed version: 0.19.3 (5c5bd46)
 - OS and Distro: Armbian (MKSPI)

Desktop:
 - OS: Windows
 - Browser : Firefox

Gcode:
[gcode.zip](https://github.com/user-attachments/files/16630983/gcode.zip)

**Comment by Donkie** [comment]
I found a big bug today when using it on my own installation that could cause this to happen. I have fixed it now and it will be released in the next update. Hopefully that prevents this from happening again :)

**Comment by Donkie** [comment]
e5f79493cc2ae8d4f778c380247284aa554464ab

**Comment by ataa** [comment]
Thanks, 
What could be the reason for those failed http requests that caused this? I have both Spoolman and moonraker on the same Pi.

**Comment by grafalex82** [comment]
This bug affected me also. Can it be released any time soon?

**Comment by ChristopherUC** [comment]
I had the same issue come up this week and I only installed about 5 days ago. Searching brought me here. What is the version this is fixed in? Also, is the only fix to delete the spool? I tried editing it and setting the weight remaining. It gives an error 500, but keeps the weight I saved, But the next time I use the spool it goes back to empty. The DB is still holding on to some sort of metric about distance used so it always resets the weight each time I use that spool.

**Comment by gjm19761** [comment]
i have the exact same issue, right density and setup in moonraker and the filament usage is much much higher than it actually is

**Comment by ChristopherUC** [comment]
I spent about 2 hours last night trying to get a dev environment setup without success so I could attempt to resolve this. I’ll jump in and try again today,I probably missed something obvious.

**Comment by gjm19761** [comment]
thanks, seems donkie pushed the fix but hasnt done a release yet, also need the docker image updated too

**Comment by Donkie** [comment]
Most likely fixed in the latest update (v0.20.0), please try it out, otherwise re-open this issue if it persists.
