### ISSUE TITLE
How can we contribute filaments to be added to the database of existing ones?

### ISSUE THREAD

**Issue by jonathanalevi** [Donkie/Spoolman#454]
I noticed that there are only select filaments from specific manufacturers such as eSun or Creality? Perhaps someone like MatterHackers would be willing to give you a database export as a form of sponsorship, so you can update the list? I should be able to facilitate a connection to get you a data export, if that helps. (PolyTerra, PolyLite ABS/ASA really stand out as missing)

**I’m already working on getting you a spreadsheet of all of the new PolyMaker SKUs and product names (they’re changing brand names to Fiberon and Panchroma)**, and I bet we can get the Hex Codes, densities, diameters, blah blah blah all in there automatically. I can work on a spreadsheet with proper formatting, just please let me know what format you need.

**Comment by alzyee** [comment]
I think it should be done here https://github.com/Donkie/SpoolmanDB

**Comment by Donkie** [comment]
Yes, please take it in that repo instead.
