### ISSUE TITLE
Spoolman used filament much to high

### ISSUE THREAD

**Issue by Razor094** [Donkie/Spoolman#472]
I have installed Spoolman and like the idea behind it. But after the first few prints I realised that the filament usage is way too high (factro 15-20). I reinstalled and checked the configuration twice, but after all I tryied out, I don't get it fixed.

I installed it on a docker container.

**Comment by jazzbassNick** [comment]
Duplicate of #451 ?

**Comment by Donkie** [comment]
Most likely fixed in the latest update (v0.20.0), please try it out, otherwise re-open this issue if it persists.
