### ISSUE TITLE
Mainsail loading error and Spoolman neither loading nor updating spools

### ISSUE THREAD

**Issue by invictus-anic3tus** [Donkie/Spoolman#481]
Hi! I have an issue regarding spoolman with mainsail. Every time I start the rPi that kipper is installed on I get this error: 

```
[server.py:load_component()] - Unable to load component: (spoolman)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/confighelper.py", line 144, in _get_option
    val = func(section, option)
  File "/usr/lib/python3.9/configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '5\n)}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/server.py", line 291, in load_component
    component = load_func(config)
  File 
"/home/pi/moonraker/moonraker/components/spoolman.py", line 30, in __init__
    self.sync_rate_seconds = config.getint("sync_rate", default=5, minval=1)
  File "/home/pi/moonraker/moonraker/confighelper.py", line 225, in getint
    return self._get_option(
  File "/home/pi/moonraker/moonraker/confighelper.py", line 153, in _get_option
    raise ConfigError(
moonraker.confighelper.ConfigError: [spoolman]: Option 'sync_rate' encountered the following error while parsing: invalid literal for int() with base 10: '5\n)}'
2024-09-09 02:19:50,001
```

In my moonraker.log. I followed all installation directions to the dot and have tried multiple ways to install spoolman. The widget does not load in the UI, but I think that the gcodes work.

**Expected behavior**
I want to see the widget and make sure everything works.

**Spoolman Host (please complete the following information):**
 - Installation type: Standalone
 - Installed version: 0.19.3
 - OS and Distro: Raspberry Pi OS (Debian?)
 - Database type: SQlite

**Desktop (please complete the following information):**
 - OS: Windows, android, iOS, mac
 - Browser: Chrome

**Comment by invictus-anic3tus** [comment]
Any help very appreciated!

**Comment by Donkie** [comment]
Looks like you have messed up the sync_rate setting in your moonraker config.

**Comment by invictus-anic3tus** [comment]
Thank you for replying! What do you suggest I change it to? It's currently set to default 5. Also: did a test print and spoolman did not calculate settings.

**Comment by invictus-anic3tus** [comment]
A-ha! Found the issue. There was a stray parenthesis a few lines after the sync rate variable that I missed. Issue resolved! Thanks Donkie for pointing me to the sync rate issue.
