### ISSUE TITLE
no port in URL after standard install

### ISSUE THREAD

**Issue by Stooovie** [Donkie/Spoolman#483]
**Describe the bug**
Standard install on Debian (Raspberry OS Lite 64bit), using the provided commands.

Install finishes, but no port is given:
![Screenshot 2024-09-15 at 9 47 50](https://github.com/user-attachments/assets/ca0b22ef-6035-42a8-aad9-1c1d982f78f9)

**Spoolman Host (please complete the following information):**
 - Installation type: standalone
 - Installed version: [e.g. 0.17.0, can be found at the bottom of your spoolman website if you don't know]
 - OS and Distro: Raspberry OS Lite 64bit

I copied the .env sample, pasted in in /Spoolman/.env and reinstalled but that's not in the instructions. The port should be filled in automatically, and it wasn't. Tried twice manually and once with KIAUH.

**Comment by erwinf** [comment]
I also got the same issue when I reinstalled spoolman on a new rpi4

**Comment by AlexTheGreat1971** [comment]
So did I

**Comment by DicyRoll** [comment]
The `install.sh` script checks if a `.env` file exists, if it doesn't it copies `.env.example` renaming it to `.env` [(link)](https://github.com/Donkie/Spoolman/blob/4f8d5abcec0e2495b1fb81befa1c14d4a405c86c/scripts/install.sh#L191-L194).
In the latest release (v0.20.0) `.env.example` is missing from the `spoolman.zip` asset that is downloaded using the standalone installation instructions.

Maybe something changed in the release workflows?

As a temporary fix I suggest omitting the execution of `install.sh` right away, so:
```bash
sudo apt-get update && \
sudo apt-get install -y curl jq && \
mkdir -p ./Spoolman && \
source_url=$(curl -s https://api.github.com/repos/Donkie/Spoolman/releases/latest | jq -r '.assets[] | select(.name == "spoolman.zip").browser_download_url') && \
curl -sSL $source_url -o temp.zip && unzip temp.zip -d ./Spoolman && rm temp.zip && \
cd ./Spoolman
```
then copying `.env.example` from the repo in your downloaded directory and finally running:
```bash
bash ./scripts/install.sh
```

**Comment by przemeku6** [comment]
same here. on proxmox vm with mint.

**Comment by AlexTheGreat1971** [comment]
> then copying `.env.example` from the repo in your downloaded directory and finally running:
> bash ./scripts/install.sh

Yes! It works. Thanks a lot

**Comment by CREEPERGAMER138** [comment]
I have not been able to make it work. I downloaded the mentioned file env.example and put it in the root of the program folder and it does not read it. Did I do it wrong or am I missing something or is it just me that is not working?
Installation from scratch first time I use the program

**Comment by CREEPERGAMER138** [comment]
> Echaré un vistazo al script de instalación, veré si algo se rompió.
> 
> Mientras tanto, el puerto se lee desde un archivo ".env" ubicado en la alfombra Spoolman. Entonces, si no tiene ese archivo, descarga el .env.example y cambia el nombre a .env, juego reinicie e intención nuevo.

![Captura de pantalla 2024-09-19 022517](https://github.com/user-attachments/assets/34195210-6815-4ea8-bc16-166ad5b28c62)
I have the same error

**Comment by mkevenaar** [comment]
> > Echaré un vistazo al script de instalación, veré si algo se rompió.
> > Mientras tanto, el puerto se lee desde un archivo ".env" ubicado en la alfombra Spoolman. Entonces, si no tiene ese archivo, descarga el .env.example y cambia el nombre a .env, juego reinicie e intención nuevo.
> 
> ![Captura de pantalla 2024-09-19 022517](https://private-user-images.githubusercontent.com/24595466/368851789-34195210-6815-4ea8-bc16-166ad5b28c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjQxNDYsIm5iZiI6MTcyNjcyMzg0NiwicGF0aCI6Ii8yNDU5NTQ2Ni8zNjg4NTE3ODktMzQxOTUyMTAtNjgxNS00ZWE4LWJjMTYtMTY2YWQ1YjI4YzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZTRmOWM0MWQwYmQ4NDM2OTNjNWY2NjlkMWE0YTk2YWQ1M2JlY2UzNDkxNmU3MzRiNTY0ZTU0ODViMDIwNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aj_IYz-tGin-EUrGebNNz2XSuJQz2u9zeA9frvIx8mw) I have the same error

It needs to be `.env`. Notice the dot (.) at the beginning of the file

**Comment by CREEPERGAMER138** [comment]
> > > Echaré un vistazo al script de instalación, veré si algo se rompió.
> > > Mientras tanto, el puerto se lee desde un archivo ".env" ubicado en la alfombra Spoolman. Entonces, si no tiene ese archivo, descarga el .env.example y cambia el nombre a .env, juego reinicie e intención nuevo.
> > 
> > 
> > ![Captura de pantalla 2024-09-19 022517](https://private-user-images.githubusercontent.com/24595466/368851789-34195210-6815-4ea8-bc16-166ad5b28c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjQxNDYsIm5iZiI6MTcyNjcyMzg0NiwicGF0aCI6Ii8yNDU5NTQ2Ni8zNjg4NTE3ODktMzQxOTUyMTAtNjgxNS00ZWE4LWJjMTYtMTY2YWQ1YjI4YzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZTRmOWM0MWQwYmQ4NDM2OTNjNWY2NjlkMWE0YTk2YWQ1M2JlY2UzNDkxNmU3MzRiNTY0ZTU0ODViMDIwNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aj_IYz-tGin-EUrGebNNz2XSuJQz2u9zeA9frvIx8mw) I have the same error
> 
> It needs to be `.env`. Notice the dot (.) at the beginning of the file

Thanks a lot

**Comment by fran6p** [comment]
I have a same issue : no .env.example so no .env. Once that file present and Spoolman.service restarted, all is OK.
When I compare the spoolman.zip from prevoius 0.19 and latest 0.20 version, the later (0.20) has none hidden files / folder in the archive.
:-)

**Comment by Donkie** [comment]
Yup seems to be a change in the CI. I have fixed the issue so the next release will include dot-files like .env.example again. For now, manually download the `.env.example` and rename it to .env
