### ISSUE TITLE
Spool: Unused (First Used at = empty) are archived

### ISSUE THREAD

**Issue by rufinus** [Donkie/Spoolman#50]
Why are not used spool archived by default?

**Comment by Donkie** [comment]
I think that would lead to a bad user experience, spools would dissappear without the user having done anything actively.

**Comment by rufinus** [comment]
thats the point... unused spools are currently only visible when "Show archived" is active.

**Comment by Donkie** [comment]
That's a bug. Did you update to 0.9.1?

**Comment by rufinus** [comment]
yes I'am on 0.9.1 just installed it and played around with it.

**Comment by Donkie** [comment]
I don't think this is an issue anymore. Please create a new issue if you have problems with archiving still.
