### ISSUE TITLE
Spoolman not showing up in mainsail/fluidd

### ISSUE THREAD

**Issue by JekleFPV** [Donkie/Spoolman#502]
**Describe the bug**
2 things actually:
- the manual install instructions result in "bash: ./scripts/install.sh: No such file or directory", seems due to it being in /home/user/Spoolman/spoolman/scripts instead of /home/user/Spoolman/scripts
fixing that manually results in a seemingly good install, but with the other issue. KIAUH also fails to install Spoolman, I suspect for the same reasons
- despite getting Spoolmans own webui working, Spoolman doesn't show up in Mainsail/Fluidd

**To Reproduce**
As mentioned above

**Expected behavior**
A Spoolman section showing up in mainsail/fluidd

**Screenshots**
<img width="1441" alt="Screenshot 2024-10-02 at 19 54 59" src="https://github.com/user-attachments/assets/15507769-64f0-4e47-996c-65de51d0d6e8">
<img width="1287" alt="Screenshot 2024-10-02 at 19 55 31" src="https://github.com/user-attachments/assets/f3478313-8fbd-409d-8031-9e4938223c88">

**Spoolman Host:**
 - Installation type: Standalone
 - Installed version: 0.20.0
 - OS and Distro: (custom) Raspbian bullseye, specifically for BTT CB1

**Desktop:**
 - OS: Mac, but also on iOS, obico and mobileraker
 - Browser: safari

**Additional context**

**Comment by jamincollins** [comment]
I believe this is due to the release archive having been altered to have a `spoolman` directory.  If you change the path to just `/home/user/Spoolman/` (dropping the extra `spoolman`) I believe things should work.

**Comment by JekleFPV** [comment]
> I believe this is due to the release archive having been altered to have a `spoolman` directory. If you change the path to just `/home/user/Spoolman/` (dropping the extra `spoolman`) I believe things should work.

That's what I did to get it installed in the first place, yet despite getting it running, it doesn't appear in mainsail/fluidd or any other frontend.

**Comment by Donkie** [comment]
yeah sorry, fixed the zip now.

**Comment by JekleFPV** [comment]
> yeah sorry, fixed the zip now.

That did the trick, thank you!
