### ISSUE TITLE
Octoprint Plugin: filament runout trigger spool change

### ISSUE THREAD

**Issue by cnance** [Donkie/Spoolman#512]
**Is your feature request related to a problem? Please describe.**
I started a print with too little filament, when the runout was detected, octoprint did not update usage in spoolman.

**Describe the solution you'd like**
I would like the octoprint plugin to trigger on filament runout so I can update/switch in the middle of a job.

**Describe alternatives you've considered**
Point me to where I should look in the code, I might be able to tweek it.

**Additional context**
I am in the middle if printing a large project (about 2kg, on two rolls). I don't want to remnants, and the prints don't line up perfectly. I started a print expecting to runout and switch rolls to finish. I expected the octoprint plugin to notice the runout event and update usage to spoolman, and let me activate another spool.

**Comment by coderjo** [comment]
The Octoprint plugin is by someone else. This appears to be related to https://github.com/mdziekon/octoprint-spoolman/issues/47
