### ISSUE TITLE
reorganize IDs

### ISSUE THREAD

**Issue by ThorPrez** [Donkie/Spoolman#528]
I´m wondering that nobody had asked for this feature.
Because I cannot see this function and I don´t wanna edit the database manually.
When I´m adding a filament or spool I´m always getting a new ID.
Would be nice to edit or reorganize the ID.

**Comment by ThorPrez** [comment]
Hi.
For example when deleting filaments or spools.
By adding a new filament or spool I'm always getting a new ID instead of a free ID.

**Comment by Donkie** [comment]
Yes, but why is that an issue?

**Comment by Donkie** [comment]
Yes I understand what you want, but why do you want it? What does it add to your experience?
