### ISSUE TITLE
Error while creating transparent filaments (status code: 422)

### ISSUE THREAD

**Issue by pejotigrek** [Donkie/Spoolman#53]
I've just got my hands on the Spoolman and even if my printer is currently down & I can't connect my Moonraker to your software - I'm on my way to build the database of used filaments :) so far - looking good! with one small issue.

when I try to set semi-transparent filament - as the color-dialogue lets me to do it:
![image](https://github.com/Donkie/Spoolman/assets/10796588/6c62ecba-42e0-470f-9439-83aa5258f653)

there is an error when trying to save this filament - and it pops up both on new filaments, and when I edit old ones and try to make them transparent:
![image](https://github.com/Donkie/Spoolman/assets/10796588/314133ea-cbb7-4be0-b5f8-0d91d436e271)

if the color setting is 100% - everything works smoothly.

if it's important for the issue, my installation is:
- docker install [via docker-compose/portainer stack]
- database used: MariaDb [also in docker]

**Comment by Donkie** [comment]
Ah. That transparency field shouldnt be there. I will remove it.

**Comment by rootiest** [comment]
Can we keep it?

I have some transparent filaments, and it would be nice to have!

**Comment by psi-4ward** [comment]
The backend validates the `color_hex` field to 6-chars but with alpha it's 8

**Comment by Donkie** [comment]
The color_hex field is just for displaying in the UI. Originally I didn't see the point in having a transparency for it, since you can't display transparency anyway. But now I realize that you could indeed incorporate that nicely in the UI. I will add support for this.

**Comment by psi-4ward** [comment]
Yeah, I would go with this diamond pattern to visualize the transparency like the picker does

**Comment by Donkie** [comment]
Resolved in 4cb2542a4171fbf9f7d19dd1054c8f78311855d7
