### ISSUE TITLE
Please help delete the [Traditional Chinese] in Weblate translation

### ISSUE THREAD

**Issue by kayzed** [Donkie/Spoolman#536]
Hello, I tried to translate the Traditional Chinese language on Weblate, but I don’t know why, 
when I added the language, it didn’t contain any reference strings. Therefore, 
I would like to ask for your help to delete the current empty Traditional Chinese translation 
so that I can add it again and translate it correctly. Thank you.

**Comment by Donkie** [comment]
I remade it for you, seems to work now. Happy translating!
