### ISSUE TITLE
Label printing

### ISSUE THREAD

**Issue by lettore** [Donkie/Spoolman#54]
Hello, this is really a nice project, it would be amazing if we can print a label directly from the web-ui with all the data of the spool.

**Comment by Donkie** [comment]
That’s a good idea! Could you make a basic mockup of how you’d want it to look?

**Comment by lettore** [comment]
There's no standard labels around, so it would be present an option to edit a template where you can choose the info you want and the size of the label, I use a standard Brother 17x54mm format usually. Then the print button should open directly a print dialog.

**Comment by Donkie** [comment]
I understand, I’d still appreciate if you gave some suggestions on how it should look like as I’m not a very good designer

**Comment by lettore** [comment]
Sure here an example from an opensource asset manager
https://snipe-it.readme.io/docs/asset-labels
![image](https://github.com/Donkie/Spoolman/assets/34779795/f4324a4f-e53f-4c36-b0fb-165e726e97bb)
ID with ID number
M as  material
V as vendor
I will add also Temperatures and Spool weight so you can calculate the remaining filament amount.

**Comment by Donkie** [comment]
Thank you!

**Comment by Donkie** [comment]
![image](https://github.com/Donkie/Spoolman/assets/2332094/4534cb73-e9cb-4e27-8d25-03a8be69d389)

**Comment by Donkie** [comment]
This is now available in release 0.10.0. Please try it out! If you have any suggestions or find any bugs, please make new issues :)

**Comment by prevail90** [comment]
can we get these labels to be able to printed via a label printer?

**Comment by a-y-m-a-n** [comment]
> can we get these labels to be able to printed via a label printer?

This is what I do but it takes some work -- so in spoolman, I have a preset for my brother label printer.  I use the 2-3/7" continuous tape (54mm).  In spoolman I pick custom size at 54x54 and then generate a bunch of labels.  When I print the printer complains about it not matching size so I need to go into the dialog and pick "2-3/7" and so on as seen below (in graphics I pick binary)..

<img width="685" height="571" alt="Image" src="https://github.com/user-attachments/assets/2d111ce9-dae4-41b0-94d1-0c2aeb2366ab" />
