### ISSUE TITLE
Can't delete Filaments

### ISSUE THREAD

**Issue by Kammi61871** [Donkie/Spoolman#551]
**Describe the bug**
Error when deleting filament (status code: 403)

**Spoolman Host (please complete the following information):**
 - Installation type: Docker
 - Installed version: 0.20
 - OS and Distro: OS: Debian GNU/Linux 12 (bookworm) aarch64
 - Database type: SQLite

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

[spoolman.log](https://github.com/user-attachments/files/17965815/spoolman.log)

**Comment by Jack1337** [comment]
Same issues here. Cant delete Filaments. Error 403

**Comment by rgmekanic** [comment]
Having the same issue. Docker install with OctoEverywhere. Also had a spool disappear.
