### ISSUE TITLE
Something in Spoolman is causing Overlay2 Dir to balloon

### ISSUE THREAD

**Issue by Senorgif2** [Donkie/Spoolman#56]
I have spoolman running on a pi4 with 8gb SD card using docker. I have no other containers running, and no other images. For some reason my overlay2 dir is 6.6 gb using about 98% of my disk. This has caused my printer to crash; that is how i found out about this problem. I've done some research and this could indicate the containers read-write layer has files being written to it by the app running inside the container. [see here](https://stackoverflow.com/questions/70354934/docker-overlay2-size-too-big) However I have no background in software or coding and I'm only able to understand so much of what is going on. Seeing as how the issue is being caused by a docker app, and spoolman is the only docker app I have, I must conclude it or my configuration is the culprit. I have no idea how to fix it.

**Comment by Donkie** [comment]
Could be the logging, but it shouldn’t grow that big. Could you run ’docker diff <container id>’ and show me what it outputs? (Run ’docker ps’ to get the container id of spoolman)

**Comment by Senorgif2** [comment]
I do apologize. I now think that there was some glitch where it was showing the total disk usage over the overlay2 dir. I looked around in the files for quite some time, none of the logs were huge. the biggest things were diff directories, but, I was impatient and reinstalled the entire OS, and with all my plugins reinstalled the disk usage is right around 6gb anyway.
