### ISSUE TITLE
Usability: Enable search & sorting for select/dropdowns

### ISSUE THREAD

**Issue by mjonuschat** [Donkie/Spoolman#60]
Many of the select/dropdown boxes would benefit from enabling search and sorting functionality, e.g. Vendor and Filament dropdowns where it's easy to accumulate dozens or hundreds of entries.

Looks like the UI is using Ant Design components, this is the feature I was thinking of: https://ant.design/components/select#select-demo-search-sort

**Comment by psi-4ward** [comment]
Search is very cool but pls also sort the entries ;)
ie  ([`localeCompare()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) with `{sensitivity: 'base'}`)
