### ISSUE TITLE
No tracking of filament usage - Unsupported url scheme?

### ISSUE THREAD

**Issue by PowerFPV** [Donkie/Spoolman#64]
Seems similar to #47 but different errors.
I am running spoolman on docker on the pi that also is hosting klipper. I've had no issues setting it up and getting it initially running, however it appears that filament usage is not being tracked. I've set it up following the guide on the github and have made the data folder, which has populated itself with spoolman.db, backups, etc.

I can confirm http://klipper.local:7125/server/spoolman/spool_id shows my actively set spool:
`{"result": {"spool_id": 1}}`

When I run commands recommended in #47 I get:                                                                                 
`pi@klipper:~ $ curl http://klipper.local:7912/api/v1/info
{"version":"0.9.1","debug_mode":false,"automatic_backups":true,"data_dir":"/home/app/.local/share/spoolman","backups_dir":"/home/app/.local/share/    `
Which to my (untrained) eyes seems to look fine? there are no explicit errors in that message that I can tell.

within moonraker.log I can see:
`Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/http_client.py", line 115, in request
    resp = await asyncio.wait_for(fut, timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 294, in run
    raise ValueError("Unsupported url scheme: %s" % self.request.url)
ValueError: Unsupported url scheme: 192.168.0.102:7912/api/v1/spool/1/use`

Which when I attempt to access the above url I get:
`{"detail":"Method Not Allowed"}`

Unfortunately I am not sure where to go from here, so any help would be greatly appreciated. I am hoping I've just made a simple mistake or missed a step and this will be an easy fix.

Thank you for your help!
[moonraker (1).log](https://github.com/Donkie/Spoolman/files/12300735/moonraker.1.log)

**Comment by Donkie** [comment]
Try adding http:// infront of the URL in your moonraker config

**Comment by PowerFPV** [comment]
That was it! Thanks very much for your quick help, can't believe I overlooked something that easy but I'm glad it wasnt a difficult fix :)

**Comment by Donkie** [comment]
No problem!
