### ISSUE TITLE
More paper size options for QR codes

### ISSUE THREAD

**Issue by samwiseg0** [Donkie/Spoolman#67]
I use a thermal printer to print my labels. The labels I use are 4x1. Would it be possible to add more options to be able to specify a custom paper size? Or more options to the page settings?

I was able to hack something together to make it print but it is less than ideal. 

ps. Thank you for adding printable QR codes. This is the last missing feature that I need to be able to move from snipe-it to spoolman.

**Comment by solo2424** [comment]
I second this, I have a Brother P-Touch and it takes different sizes. Right now I have 1.17" roll in.

**Comment by Donkie** [comment]
Ah, I didn't consider any other than standard paper sizes but of course rolls exist :P. I will add the ability for manually specifying paper size
