### ISSUE TITLE
Printer Layout Settings

### ISSUE THREAD

**Issue by solo2424** [Donkie/Spoolman#73]
I appreciate you adding custom sizes. I do have one more somewhat minor issue. Eventhough I have the Column and Row set to 1x1. it is still by default showing 3 rows. Not that big of a deal but if I forget to select the page to print to 1, it prints two blanks. 

![image](https://github.com/Donkie/Spoolman/assets/1903450/8176f565-0be5-40a0-ac58-5c79f38250e9)

![image](https://github.com/Donkie/Spoolman/assets/1903450/d250c48f-2a29-4077-a6c2-c270c585b02d)

**Comment by samwiseg0** [comment]
I noticed this as well. Possibly a bug?
