### ISSUE TITLE
permissions issue?

### ISSUE THREAD

**Issue by Digityle** [Donkie/Spoolman#75]
Hello, I'm trying to set up spoolman (finally got my printer back) but I'm running into permissions error Errno 13] Permission denied: '/home/app/.local/share/spoolman/spoolman.log', I'm certain I screwed up something when trying to install docker but was hoping you could point me in the right direction? I tried running chown 1000:1000 as described but no dice...

**Comment by akonkol** [comment]
did you run the command including the word "data"?
`chown 1000:1000 data`

**Comment by Digityle** [comment]
I did.

**Comment by Donkie** [comment]
@Digityle did you manage to resolve this issue?

**Comment by stelladraco27** [comment]
I'm having the same issue; however, after trying to chown all the directories and files, it still won't start. I created an issue as well in relation to this. It's weird because I had it working not 3 weeks ago. Any help would be very much appreciated.
