### ISSUE TITLE
Help: {"detail":"Not Found"} error

### ISSUE THREAD

**Issue by Larry3best** [Donkie/Spoolman#8]
While I can interact with the web interface, I am unable to use any API requests as it returns `{"detail":"Not Found"}`. Refreshing the web interface also shows the same error. It's my first time working with API request sbut I looked up the proper formatting (i.e http://my-ip:7912/vendor?name=test). Thanks in advance.

**Comment by Donkie** [comment]
The API endpoint is at /api/v1, so try something like

http://myip:7912/api/v1/vendor?name=test

**Comment by Larry3best** [comment]
Thank you
