### ISSUE TITLE
Export generated label as image (png, jpg)

### ISSUE THREAD

**Issue by goodwin** [Donkie/Spoolman#80]
It will be fantastic to have the ability to get the label as a small image file (png or jpg format).
This can be used for portable label printers like Niimbot (that can't be used as a regular printer, but needs its own software). Such printers can insert images in the internal editor to print labels.

**Comment by TjardF** [comment]
yeah, would be awesome for my old Dymo

**Comment by Bloodpack** [comment]
This would be really nice
