### ISSUE TITLE
Label print question

### ISSUE THREAD

**Issue by ThoughtfulDev** [Donkie/Spoolman#83]
Just found the project and i wondered on how to get the labels on the spool. Do you just cut them with a scissor or are the label printer who work well with Spoolman?

**Comment by Donkie** [comment]
I personally use A4-sized address/label sticker paper, e.g. https://www.amazon.co.uk/Avery-Adhesive-Address-Printers-QuickDRY/dp/B000RFBTY4 (there are a million different brands that do these)

They work in regular printers :)

Others in the community are using dedicated label printers, like Brother QL-800 for example, which Spoolman also supports.
