### ISSUE TITLE
The page is not served over HTTPS

### ISSUE THREAD

**Issue by dualznz** [Donkie/Spoolman#87]
Im trying to use my camera to take photos but i keep getting this error.

i have not exposed spoolman to the outside world as there is no login structure and thus https is not needed.

how can we get the camera to work or does it have to be exposed

**Comment by Donkie** [comment]
Unfortunately, it's a browser security limitation preventing us from using the camera on http sites. You can make a reverse proxy using nginx to serve https with a self-signed or letsencrypt certificate to get https.

**Comment by dualznz** [comment]
yea i know how to do that, stupid browsers lol

cheers anyways
