### ISSUE TITLE
Add a price for each spool

### ISSUE THREAD

**Issue by sudermanjr** [Donkie/Spoolman#88]
I often buy spools at wholesale/bulk prices and then buy one or two more later at MSRP.

It would be really nice to have the filament price be my MSRP, and then be able to put in the price I paid for each spool.

This is something I would be willing to contribute to the backend if it's a feature folks want, but I'm terrible at JS so the Frontend may be out for me

P.S. Thanks for this project, it's exactly what I needed.

**Comment by Donkie** [comment]
Yes, a price field on spools is something others have suggested as well. Definitely something worth adding!

**Comment by ThomasHineXYZ** [comment]
This would definitely be appreciated.
Filament spool prices aren't always consistent. On top of that, there might be a sale or coupon or something.

**Comment by pdsccode** [comment]
Adding my interest here as I just reordered a new spool of an already in my DB existing filament for a different price. 🙂
