### ISSUE TITLE
data folder empty

### ISSUE THREAD

**Issue by solo2424** [Donkie/Spoolman#9]
Hello, 

I am not sure what I am doing wrong, but I ran the docker-compose.yml and it looks as if it installed, but the portal doesn't load. As I looked into this, the data folder is empty. Any idea what I may be doing wrong. Can anyone help me out?

**Comment by Donkie** [comment]
Can you show me the exact docker-compose you run?

What URL did you put in your browser?

**Comment by solo2424** [comment]
Here is the docker-compose.yml. I used the exact same file and ran it on my windows PC and it works fine. After creating the docker-compose.yml I run the following command. sudo docker-compose up -d. I now get the following message. But the url still does not work. http://192.168.0.93:7912

spoolman_spoolman_1 is up-to-date

docker-compose.yml

version: '3.8'
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      - ./data:/home/app/.local/share/spoolman
    ports:
      - "7912:8000"

**Comment by Donkie** [comment]
Everything looks correct from what I can see. Can you show me the output of
```
sudo docker logs $(sudo docker ps -aqf "name=spoolman_spoolman_1")
```

**Comment by solo2424** [comment]
[spoolman.log](https://github.com/Donkie/Spoolman/files/11859775/spoolman.log)
I appreciate you helping me with this. I really hope to get this off of my desktop and onto my server. Looking at the log (i'm no programmer) it looks like this is a permission issue.

**Comment by Donkie** [comment]
Ah, I was able to reproduce this locally. An data directory empty should appear in the same directory as your docker-compose.yml, do `sudo chown 1000:1000 data` on that data folder and restart your docker container, and it should now work!

A spoolman.db file should appear in the data folder as well.

**Comment by solo2424** [comment]
That did it! thank you so much! Like I said before, this project is so needed! I appreciate your efforts. I would love to donate to this cause if you have a method. Also, Is there a way to submit feature requests? I can submit issues but not sure if that is the best route to go. I have some good suggestions that I think would help alot. Of course, I know you are waiting to see if it gets added to the master branch.

**Comment by Donkie** [comment]
Thank you for the nice feedback :) For now you can use https://paypal.me/donkieyo if you want to donate

Please make issues here on github.com if you want to submit any feature requests, it's the best place for it!

**Comment by solo2424** [comment]
I ran a few prints but the estimated remaining  weight has not adusted. I waited quite a while to see if it just takes time to sync but nothing. Here is the command I get that verifies (I believe so) I selected the correct spool.


solo@SoLoServer:~/Spoolman$ POST 192.168.0.93:7126/spoolman/set_spool
Please enter content (application/x-www-form-urlencoded) to be POSTed:
{"spool_id": 7}{"result": true}solo@SoLoServer:~/Spoolman$

**Comment by Donkie** [comment]
Interesting. Could you show me the logs of Spoolman, and also the logs of Moonraker?

**Comment by solo2424** [comment]
[spoolman2.log](https://github.com/Donkie/Spoolman/files/11860619/spoolman2.log)
[moonraker (1).log](https://github.com/Donkie/Spoolman/files/11860621/moonraker.1.log)

**Comment by Donkie** [comment]
Looks like you're not setting the spool correctly:
```
2023-06-25 10:54:40,202 [spoolman.py:set_active_spool()] - Setting active spool to: None
2023-06-25 10:54:40,202 [database.py:_insert_impl()] - Error inserting key '['spoolman.active_spool_id']' in namespace 'spoolman'
```

It's interpreting your spool setting request as if you want to un-set the spool_id for some reason. That should work in either case though.

Maybe your method of sending a POST request is flawed? Try running this unix curl command on your server, replacing the spool ID and the IP&port for your moonraker instance of course:
```
curl -X POST -H "Content-Type: application/json" -d '{"spool_id": 123}' http://192.168.0.123:1234/spoolman/set_spool
```

**Comment by solo2424** [comment]
That did it! Thanks, and good luck with your PR I am glad to see that Arksine is checking it out.

**Comment by Donkie** [comment]
No problem! I have made some updates in the PR now to address the review comments. Would be nice if you fetch the latest changes (using same approach as last time to pull them in) and test it out.

Note that the command to set the spool ID has been updated, the curl command would now be:

```
curl -X POST -H "Content-Type: application/json" -d '{"spool_id": 123}' http://192.168.0.123:1234/spoolman/spool_id
```

**Comment by solo2424** [comment]
So I wentthrough the same process to switch over to your branch but I don't think it is updating. It says "Your branch is up to date" but the new curl command is not working. The old command still appears to work.  Here are the commands and responses.

[Spoolman cmd.txt](https://github.com/Donkie/Spoolman/files/11861138/Spoolman.cmd.txt)

**Comment by Donkie** [comment]
Strange.
In any case, it seems like the PR will get merged quite soon, so just sit tight for that :)
