### ISSUE TITLE
Unable to create spools/filaments/vendors - shows a white screen

### ISSUE THREAD

**Issue by Vanilla009** [Donkie/Spoolman#91]
I have spoolman installed with docker and I can see the dashboard, but cannot create anything. It takes me to a white screen if I try to create anything. I did change the version identifier in the docker-compose.yml to 3.3 because it threw errors because of the 3.8 version. The URL it takes me to looks fine. I have attached the log and yaml files.
[spoolman.log](https://github.com/Donkie/Spoolman/files/12446945/spoolman.log)
[docker-compose.yml.txt](https://github.com/Donkie/Spoolman/files/12446950/docker-compose.yml.txt)

**Comment by Donkie** [comment]
What browser are you using, and what version?

**Comment by Vanilla009** [comment]
Google Chrome, Latest release. Version 116.0.5845.111

**Comment by Vanilla009** [comment]
I got it fixed. I ran chown 1000:1000 data in the my spoolman folder and that seemed to fix the issue. Thank you!

**Comment by Vanilla009** [comment]
I got it fixed. I ran chown 1000:1000 data in the my spoolman folder and that seemed to fix the issue. Thank you!
