### ISSUE TITLE
Used filament gets substracted wrong

### ISSUE THREAD

**Issue by exen904** [Donkie/Spoolman#93]
I just got this up and running, and I noticed something strange after a test print. I use fluidd as frontend (though Mainsail is also installed), selected the spool in the start print dialog, and after printing, my filament usage looks like this:

![image](https://github.com/Donkie/Spoolman/assets/59537420/4d47d9cd-dd46-487a-8aab-88704060be14)
![image](https://github.com/Donkie/Spoolman/assets/59537420/af65bff0-31b4-4af0-83e5-bb8e76ec7fc9)

It seems like that the used filament in g gets converted in some kind of other dimensions here. If you need any log files just let me know, I was not just sure now what to collect where in this case. 

Docker logs with the last 1000 lines attached
[_spoolman-spoolman-1_logs(1).txt](https://github.com/Donkie/Spoolman/files/12480506/_spoolman-spoolman-1_logs.1.txt)

Versions:

- MainsailOS 1.0.1 
- Fluidd v1.25.2 
- moonraker v0.8.0-138-gfe120952

**Comment by Donkie** [comment]
Can you show me all the settings for your filament and spool items?

**Comment by exen904** [comment]
![image](https://github.com/Donkie/Spoolman/assets/59537420/e3fc1b60-8d6f-493a-8f40-e7aede6c9a4d)

![image](https://github.com/Donkie/Spoolman/assets/59537420/f447fa80-ff20-4edf-80ca-a161ec85e827)

**Comment by Donkie** [comment]
This must be a moonraker or klipper issue. Perhaps the extruder steps are being calculated incorrectly for your printer or something. Please create an issue in the moonraker github.
